namespace Dominio.DTO.Flota;
public class FlotaItemDto{public string Codigo{get;set;}="";public string Nombre{get;set;}="";public string Cobrable{get;set;}="N";}
public class FlotaVehiculoDto{public int IdVehiculo{get;set;}public string Placa{get;set;}="";public string Marca{get;set;}="";public string Modelo{get;set;}="";public int Anio{get;set;}public string Color{get;set;}="";public decimal GalonesTanque{get;set;}public decimal PrecioGalon{get;set;}public decimal RendimientoTanqueKm{get;set;}public string Compartido{get;set;}="N";}
public class FlotaChoferDto{public int IdChofer{get;set;}public string Nombres{get;set;}="";public string Documento{get;set;}="";public string Telefono{get;set;}="";public string Licencia{get;set;}="";}
public class FlotaCatalogosDto{public List<FlotaItemDto> Modalidades{get;set;}=new();public List<FlotaItemDto> Motivos{get;set;}=new();public List<FlotaVehiculoDto> Vehiculos{get;set;}=new();public List<FlotaChoferDto> Choferes{get;set;}=new();}
public class FlotaVehiculoCrearDto{public string Placa{get;set;}="";public string Marca{get;set;}="";public string Modelo{get;set;}="";public int? Anio{get;set;}public string? Color{get;set;}public decimal? GalonesTanque{get;set;}public decimal? PrecioGalon{get;set;}public decimal? RendimientoTanqueKm{get;set;}public bool Compartido{get;set;}}
public class FlotaChoferCrearDto{public string? Documento{get;set;}public string Nombres{get;set;}="";public string? Telefono{get;set;}public string? Licencia{get;set;}}
public class FlotaContratoCrearDto{public int IdVehiculo{get;set;}public int IdChofer{get;set;}public string Modalidad{get;set;}="";public string Periodicidad{get;set;}="S";public DateTime FechaInicio{get;set;}public DateTime? FechaFin{get;set;}public decimal TarifaDia{get;set;}public bool CobraDomingo{get;set;}public bool ControlKm{get;set;}public string? Observacion{get;set;}}
public class FlotaTrabajoDiaDto{public int IdContrato{get;set;}public DateTime Fecha{get;set;}public bool Trabajo{get;set;}public string CodMotivo{get;set;}="";public bool Cobrable{get;set;}public decimal? KmInicial{get;set;}public decimal? KmFinal{get;set;}public decimal ImporteCombustible{get;set;}public decimal Galones{get;set;}public string? PagoCombustible{get;set;}public string? Observacion{get;set;}}
public class FlotaDashboardDto{public int IdContrato{get;set;}public string Numero{get;set;}="";public string Placa{get;set;}="";public string Vehiculo{get;set;}="";public string Chofer{get;set;}="";public string ModalidadCodigo{get;set;}="";public string Modalidad{get;set;}="";public DateTime FechaInicio{get;set;}public DateTime? FechaFin{get;set;}public decimal TarifaDia{get;set;}public string ControlKm{get;set;}="N";public string TrabajoHoy{get;set;}="";public string MotivoHoy{get;set;}="";public decimal ImporteHoy{get;set;}public decimal TotalGenerado{get;set;}public int DiasRegistrados{get;set;}public decimal KmAcumulado{get;set;}public decimal CombustibleAportado{get;set;}public decimal ConsumoEstimado{get;set;}public decimal BalanceCombustible=>CombustibleAportado-ConsumoEstimado;}
public class FlotaResultadoDto{public bool Ok{get;set;}public int Id{get;set;}public string Mensaje{get;set;}="";}
