namespace Dominio.DTO.Flota;
public class FlotaContratoAdminDto{public int IdContrato{get;set;}public string Numero{get;set;}="";public string Placa{get;set;}="";public string Chofer{get;set;}="";public string ModalidadCodigo{get;set;}="";public string Modalidad{get;set;}="";public decimal TarifaDia{get;set;}public string Periodicidad{get;set;}="S";public DateTime FechaInicio{get;set;}public DateTime? FechaFin{get;set;}public string Estado{get;set;}="";public decimal TotalRecibos{get;set;}public decimal TotalPagado{get;set;}public decimal Saldo{get;set;}}
public class FlotaCalendarioDto{public FlotaCalendarioContratoDto? Contrato{get;set;}public List<FlotaCalendarioDiaDto> Dias{get;set;}=new();public List<FlotaItemDto> MediosPago{get;set;}=new();}
public class FlotaCalendarioContratoDto{public int IdContrato{get;set;}public string Numero{get;set;}="";public string Placa{get;set;}="";public string Vehiculo{get;set;}="";public string Chofer{get;set;}="";public string Modalidad{get;set;}="";public decimal TarifaDia{get;set;}public string Periodicidad{get;set;}="";}
public class FlotaCalendarioDiaDto{public int IdOperacionDia{get;set;}public DateTime Fecha{get;set;}public DateTime? FechaHoraInicio{get;set;}public DateTime? FechaHoraFin{get;set;}public string Trabajo{get;set;}="";public string CodMotivo{get;set;}="";public string Motivo{get;set;}="";public string Cobrable{get;set;}="";public decimal Importe{get;set;}public decimal Km{get;set;}public decimal? KmInicial{get;set;}public decimal? KmFinal{get;set;}public string Observacion{get;set;}="";public string Origen{get;set;}="";public string TieneRecibo{get;set;}="N";}
public class FlotaReciboGenerarDto{public int IdContrato{get;set;}public DateTime FechaInicio{get;set;}public DateTime FechaFin{get;set;}public string? Observacion{get;set;}}
public class FlotaReciboManualDto{public int IdContrato{get;set;}public List<DateTime> Fechas{get;set;}=new();public decimal TarifaDia{get;set;}public string ModoAgrupacion{get;set;}="U";public string? Observacion{get;set;}}
public class FlotaPagoReciboDto{public int IdReciboAlquiler{get;set;}public DateTime FechaPago{get;set;}public decimal Importe{get;set;}public string MedioPago{get;set;}="";public string? FotoVoucher{get;set;}public string? Observacion{get;set;}public bool Validado{get;set;}}
public class FlotaReciboDto{public int IdReciboAlquiler{get;set;}public string Numero{get;set;}="";public DateTime FechaEmision{get;set;}public DateTime FechaInicio{get;set;}public DateTime FechaFin{get;set;}public int CantidadDias{get;set;}public decimal TarifaDia{get;set;}public decimal ImporteTotal{get;set;}public decimal ImportePagado{get;set;}public decimal Saldo{get;set;}public string EstadoCodigo{get;set;}="";public string Estado{get;set;}="";public string Origen{get;set;}="";public string Observacion{get;set;}="";}
public class FlotaReciboDetalleDto{public FlotaReciboDocumentoDto? Cabecera{get;set;}public List<FlotaReciboDiaDto> Dias{get;set;}=new();public List<FlotaReciboPagoDto> Pagos{get;set;}=new();}
public class FlotaReciboDocumentoDto:FlotaReciboDto{public int IdContrato{get;set;}public string Contrato{get;set;}="";public string Placa{get;set;}="";public string Chofer{get;set;}="";}
public class FlotaReciboDiaDto{public int IdDetalle{get;set;}public int IdOperacionDia{get;set;}public DateTime Fecha{get;set;}public decimal TarifaDia{get;set;}public decimal Importe{get;set;}public string Origen{get;set;}="";public string Observacion{get;set;}="";}
public class FlotaReciboPagoDto{public int IdPago{get;set;}public DateTime FechaPago{get;set;}public decimal Importe{get;set;}public string MedioPago{get;set;}="";public string MedioPagoTexto{get;set;}="";public string FotoVoucher{get;set;}="";public string Observacion{get;set;}="";public string Validado{get;set;}="N";public string FlgEstado{get;set;}="A";}
public class FlotaReciboResultadoDto:FlotaResultadoDto{public int Cantidad{get;set;}}
public class FlotaReciboAnularDto{public int IdReciboAlquiler{get;set;}public string Motivo{get;set;}="";}
public class FlotaReciboQuitarDiaDto{public int IdReciboDetalle{get;set;}public string Motivo{get;set;}="";}
public class FlotaPagoReciboEditarDto{public int IdPagoRecibo{get;set;}public DateTime FechaPago{get;set;}public decimal Importe{get;set;}public string MedioPago{get;set;}="";public string? FotoVoucher{get;set;}public string? Observacion{get;set;}public string Motivo{get;set;}="";}
public class FlotaPagoReciboAnularDto{public int IdPagoRecibo{get;set;}public string Motivo{get;set;}="";}
public class FlotaPagoReciboValidarDto{public int IdPagoRecibo{get;set;}public string FlgValidado{get;set;}="N";public string Motivo{get;set;}="";}
public class FlotaOperacionDiaCorregirDto{public int IdOperacionDia{get;set;}public string FlgTrabajo{get;set;}="N";public string CodMotivo{get;set;}="";public string FlgCobrable{get;set;}="N";public decimal? KmInicial{get;set;}public decimal? KmFinal{get;set;}public DateTime? FechaHoraInicio{get;set;}public DateTime? FechaHoraFin{get;set;}public string? Observacion{get;set;}public string Motivo{get;set;}="";}
