SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF SCHEMA_ID('flota') IS NULL EXEC('CREATE SCHEMA flota');
GO
IF OBJECT_ID('flota.modalidad','U') IS NULL CREATE TABLE flota.modalidad(Cod_Modalidad VARCHAR(1) NOT NULL PRIMARY KEY,Nombre VARCHAR(40) NOT NULL,Flg_Activo VARCHAR(1) NOT NULL DEFAULT('S'));
IF NOT EXISTS(SELECT 1 FROM flota.modalidad WHERE Cod_Modalidad='D') INSERT flota.modalidad VALUES('D','Alquiler diario','S');
IF NOT EXISTS(SELECT 1 FROM flota.modalidad WHERE Cod_Modalidad='L') INSERT flota.modalidad VALUES('L','Puerta libre','S');
GO
IF OBJECT_ID('flota.motivo_dia','U') IS NULL CREATE TABLE flota.motivo_dia(Cod_Motivo VARCHAR(3) NOT NULL PRIMARY KEY,Nombre VARCHAR(80) NOT NULL,Flg_Cobrable VARCHAR(1) NOT NULL DEFAULT('N'),Flg_Activo VARCHAR(1) NOT NULL DEFAULT('S'),Orden INT NOT NULL DEFAULT(0));
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='TRA') INSERT flota.motivo_dia VALUES('TRA','Dia trabajado','S','S',1);
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='DES') INSERT flota.motivo_dia VALUES('DES','Descanso acordado','N','S',2);
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='MAN') INSERT flota.motivo_dia VALUES('MAN','Mantenimiento aprobado','N','S',3);
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='AVE') INSERT flota.motivo_dia VALUES('AVE','Averia del vehiculo','N','S',4);
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='FAL') INSERT flota.motivo_dia VALUES('FAL','Falta del conductor','S','S',5);
IF NOT EXISTS(SELECT 1 FROM flota.motivo_dia WHERE Cod_Motivo='OTR') INSERT flota.motivo_dia VALUES('OTR','Otro motivo autorizado','N','S',99);
GO
IF COL_LENGTH('flota.vehiculo','id_empresa') IS NULL ALTER TABLE flota.vehiculo ADD id_empresa INT NOT NULL CONSTRAINT DF_flota_vehiculo_empresa DEFAULT(6);
IF COL_LENGTH('flota.vehiculo','id_est') IS NULL ALTER TABLE flota.vehiculo ADD id_est CHAR(2) NOT NULL CONSTRAINT DF_flota_vehiculo_est DEFAULT('4');
IF COL_LENGTH('flota.vehiculo','MarcaTexto') IS NULL ALTER TABLE flota.vehiculo ADD MarcaTexto VARCHAR(50) NULL;
IF COL_LENGTH('flota.vehiculo','ModeloTexto') IS NULL ALTER TABLE flota.vehiculo ADD ModeloTexto VARCHAR(60) NULL;
IF COL_LENGTH('flota.vehiculo','ColorTexto') IS NULL ALTER TABLE flota.vehiculo ADD ColorTexto VARCHAR(30) NULL;
IF COL_LENGTH('flota.vehiculo','GalonesTanque') IS NULL ALTER TABLE flota.vehiculo ADD GalonesTanque DECIMAL(10,3) NULL;
IF COL_LENGTH('flota.vehiculo','PrecioGalon') IS NULL ALTER TABLE flota.vehiculo ADD PrecioGalon DECIMAL(10,2) NULL;
IF COL_LENGTH('flota.vehiculo','RendimientoTanqueKm') IS NULL ALTER TABLE flota.vehiculo ADD RendimientoTanqueKm DECIMAL(10,2) NULL;
IF COL_LENGTH('flota.vehiculo','Flg_Compartido') IS NULL ALTER TABLE flota.vehiculo ADD Flg_Compartido VARCHAR(1) NOT NULL CONSTRAINT DF_flota_vehiculo_comp DEFAULT('N');
GO
IF COL_LENGTH('flota.chofer','Id_Chofer') IS NULL ALTER TABLE flota.chofer ADD Id_Chofer INT IDENTITY(1,1) NOT NULL;
IF COL_LENGTH('flota.chofer','id_empresa') IS NULL ALTER TABLE flota.chofer ADD id_empresa INT NOT NULL CONSTRAINT DF_flota_chofer_empresa DEFAULT(6);
IF COL_LENGTH('flota.chofer','id_est') IS NULL ALTER TABLE flota.chofer ADD id_est CHAR(2) NOT NULL CONSTRAINT DF_flota_chofer_est DEFAULT('4');
IF COL_LENGTH('flota.chofer','Nombres') IS NULL ALTER TABLE flota.chofer ADD Nombres VARCHAR(120) NULL;
IF COL_LENGTH('flota.chofer','Documento') IS NULL ALTER TABLE flota.chofer ADD Documento VARCHAR(15) NULL;
IF COL_LENGTH('flota.chofer','Telefono') IS NULL ALTER TABLE flota.chofer ADD Telefono VARCHAR(20) NULL;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('flota.chofer') AND name='UX_flota_chofer_id') CREATE UNIQUE INDEX UX_flota_chofer_id ON flota.chofer(Id_Chofer);
GO
IF OBJECT_ID('flota.contrato','U') IS NULL
CREATE TABLE flota.contrato(Id_Contrato INT IDENTITY(1,1) NOT NULL PRIMARY KEY,Numero VARCHAR(20) NULL,id_empresa INT NOT NULL,id_est CHAR(2) NOT NULL,Id_Vehiculo INT NOT NULL,Id_Chofer INT NOT NULL,Cod_Modalidad VARCHAR(1) NOT NULL,FechaInicio DATE NOT NULL,FechaFin DATE NULL,TarifaDia DECIMAL(18,2) NOT NULL,Flg_CobraDomingo VARCHAR(1) NOT NULL DEFAULT('N'),Flg_ControlKm VARCHAR(1) NOT NULL DEFAULT('N'),Observacion VARCHAR(300) NULL,Flg_Estado VARCHAR(1) NOT NULL DEFAULT('A'),Usu_Creacion INT NOT NULL,Fec_Creacion DATETIME NOT NULL DEFAULT(GETDATE()),CONSTRAINT FK_flota_contrato_vehiculo FOREIGN KEY(Id_Vehiculo) REFERENCES flota.vehiculo(Id_Vehiculo),CONSTRAINT FK_flota_contrato_chofer FOREIGN KEY(Id_Chofer) REFERENCES flota.chofer(Id_Chofer),CONSTRAINT FK_flota_contrato_modalidad FOREIGN KEY(Cod_Modalidad) REFERENCES flota.modalidad(Cod_Modalidad));
GO
IF OBJECT_ID('flota.operacion_dia','U') IS NULL
CREATE TABLE flota.operacion_dia(Id_OperacionDia INT IDENTITY(1,1) NOT NULL PRIMARY KEY,id_empresa INT NOT NULL,id_est CHAR(2) NOT NULL,Id_Contrato INT NOT NULL,Fecha DATE NOT NULL,Flg_Trabajo VARCHAR(1) NOT NULL,Cod_Motivo VARCHAR(3) NOT NULL,Flg_Cobrable VARCHAR(1) NOT NULL,ImporteGenerado DECIMAL(18,2) NOT NULL,KmInicial DECIMAL(12,2) NULL,KmFinal DECIMAL(12,2) NULL,KmRecorrido AS(CASE WHEN KmFinal>=KmInicial THEN KmFinal-KmInicial ELSE 0 END) PERSISTED,ImporteCombustible DECIMAL(18,2) NOT NULL DEFAULT(0),GalonesCargados DECIMAL(12,3) NOT NULL DEFAULT(0),Flg_PagoCombustible VARCHAR(1) NULL,CostoConsumoEstimado DECIMAL(18,2) NOT NULL DEFAULT(0),Observacion VARCHAR(300) NULL,Usu_Creacion INT NOT NULL,Fec_Creacion DATETIME NOT NULL DEFAULT(GETDATE()),Usu_Modif INT NULL,Fec_Modif DATETIME NULL,CONSTRAINT UQ_flota_operacion_dia UNIQUE(Id_Contrato,Fecha),CONSTRAINT FK_flota_operacion_contrato FOREIGN KEY(Id_Contrato) REFERENCES flota.contrato(Id_Contrato),CONSTRAINT FK_flota_operacion_motivo FOREIGN KEY(Cod_Motivo) REFERENCES flota.motivo_dia(Cod_Motivo),CONSTRAINT CK_flota_operacion_km CHECK(KmFinal IS NULL OR KmInicial IS NULL OR KmFinal>=KmInicial));
GO
IF OBJECT_ID('flota.p_catalogos','P') IS NOT NULL DROP PROCEDURE flota.p_catalogos;
GO
CREATE PROCEDURE flota.p_catalogos @id_empresa INT,@id_est CHAR(2) AS BEGIN SET NOCOUNT ON;SELECT Cod_Modalidad Codigo,Nombre FROM flota.modalidad WHERE Flg_Activo='S' ORDER BY Nombre;SELECT Cod_Motivo Codigo,Nombre,Flg_Cobrable FROM flota.motivo_dia WHERE Flg_Activo='S' ORDER BY Orden;SELECT Id_Vehiculo,Placa,ISNULL(MarcaTexto,'') Marca,ISNULL(ModeloTexto,'') Modelo,ISNULL(Anio_Modelo,ISNULL(Anio_Fabricacion,0)) Anio,ISNULL(ColorTexto,'') Color,ISNULL(GalonesTanque,0) GalonesTanque,ISNULL(PrecioGalon,0) PrecioGalon,ISNULL(RendimientoTanqueKm,0) RendimientoTanqueKm,Flg_Compartido FROM flota.vehiculo WHERE id_empresa=@id_empresa AND id_est=@id_est AND flg_activo=1 ORDER BY Placa;SELECT Id_Chofer,ISNULL(NULLIF(Nombres,''),Cod_TipAnex+'-'+Cod_Anxo) Nombres,ISNULL(Documento,'') Documento,ISNULL(Telefono,'') Telefono,ISNULL(Nro_Licencia,'') Licencia FROM flota.chofer WHERE id_empresa=@id_empresa AND id_est=@id_est AND Activo=1 ORDER BY Nombres;END
GO
IF OBJECT_ID('flota.p_vehiculo_crear','P') IS NOT NULL DROP PROCEDURE flota.p_vehiculo_crear;
GO
CREATE PROCEDURE flota.p_vehiculo_crear @id_empresa INT,@id_est CHAR(2),@Placa VARCHAR(10),@Marca VARCHAR(50),@Modelo VARCHAR(60),@Anio INT=NULL,@Color VARCHAR(30)=NULL,@GalonesTanque DECIMAL(10,3)=NULL,@PrecioGalon DECIMAL(10,2)=NULL,@RendimientoTanqueKm DECIMAL(10,2)=NULL,@Compartido BIT=0,@Usuario INT,@Id INT OUTPUT,@Mensaje VARCHAR(250) OUTPUT AS BEGIN SET NOCOUNT ON;SET @Id=0;IF EXISTS(SELECT 1 FROM flota.vehiculo WHERE id_empresa=@id_empresa AND Placa=UPPER(LTRIM(RTRIM(@Placa)))) BEGIN SET @Mensaje='La placa ya existe.';RETURN;END;INSERT flota.vehiculo(Placa,Anio_Fabricacion,Anio_Modelo,Tiene_GPS,flg_activo,Fec_Creac,Usu_Creac,Fec_Modif,Usu_Modif,id_empresa,id_est,MarcaTexto,ModeloTexto,ColorTexto,GalonesTanque,PrecioGalon,RendimientoTanqueKm,Flg_Compartido) VALUES(UPPER(LTRIM(RTRIM(@Placa))),@Anio,@Anio,0,1,GETDATE(),CONVERT(VARCHAR(20),@Usuario),GETDATE(),CONVERT(VARCHAR(20),@Usuario),@id_empresa,@id_est,@Marca,@Modelo,@Color,@GalonesTanque,@PrecioGalon,@RendimientoTanqueKm,CASE WHEN @Compartido=1 THEN 'S' ELSE 'N' END);SET @Id=SCOPE_IDENTITY();SET @Mensaje='Vehiculo registrado.';END
GO
IF OBJECT_ID('flota.p_chofer_crear','P') IS NOT NULL DROP PROCEDURE flota.p_chofer_crear;
GO
CREATE PROCEDURE flota.p_chofer_crear @id_empresa INT,@id_est CHAR(2),@Documento VARCHAR(15)=NULL,@Nombres VARCHAR(120),@Telefono VARCHAR(20)=NULL,@Licencia VARCHAR(30)=NULL,@Usuario INT,@Id INT OUTPUT,@Mensaje VARCHAR(250) OUTPUT AS BEGIN SET NOCOUNT ON;SET @Id=0;DECLARE @Anxo CHAR(6);SELECT @Anxo=RIGHT('000000'+CONVERT(VARCHAR(6),ISNULL(MAX(TRY_CONVERT(INT,Cod_Anxo)),0)+1),6) FROM flota.chofer WHERE Cod_TipAnex='F';INSERT flota.chofer(Cod_TipAnex,Cod_Anxo,Nro_Licencia,Activo,Fec_Creac,Usu_Creac,id_empresa,id_est,Nombres,Documento,Telefono) VALUES('F',@Anxo,@Licencia,1,GETDATE(),CONVERT(VARCHAR(20),@Usuario),@id_empresa,@id_est,UPPER(LTRIM(RTRIM(@Nombres))),@Documento,@Telefono);SET @Id=SCOPE_IDENTITY();SET @Mensaje='Conductor registrado.';END
GO
IF OBJECT_ID('flota.p_contrato_crear','P') IS NOT NULL DROP PROCEDURE flota.p_contrato_crear;
GO
CREATE PROCEDURE flota.p_contrato_crear @id_empresa INT,@id_est CHAR(2),@IdVehiculo INT,@IdChofer INT,@Modalidad VARCHAR(1),@FechaInicio DATE,@FechaFin DATE=NULL,@TarifaDia DECIMAL(18,2),@CobraDomingo BIT=0,@ControlKm BIT=0,@Observacion VARCHAR(300)=NULL,@Usuario INT,@Id INT OUTPUT,@Mensaje VARCHAR(250) OUTPUT AS BEGIN SET NOCOUNT ON;SET @Id=0;IF @TarifaDia<=0 BEGIN SET @Mensaje='La tarifa debe ser mayor a cero.';RETURN;END;IF EXISTS(SELECT 1 FROM flota.contrato WHERE id_empresa=@id_empresa AND Id_Vehiculo=@IdVehiculo AND Flg_Estado='A') BEGIN SET @Mensaje='El vehiculo ya tiene un contrato activo.';RETURN;END;INSERT flota.contrato(id_empresa,id_est,Id_Vehiculo,Id_Chofer,Cod_Modalidad,FechaInicio,FechaFin,TarifaDia,Flg_CobraDomingo,Flg_ControlKm,Observacion,Usu_Creacion) VALUES(@id_empresa,@id_est,@IdVehiculo,@IdChofer,@Modalidad,@FechaInicio,@FechaFin,@TarifaDia,CASE WHEN @CobraDomingo=1 THEN 'S' ELSE 'N' END,CASE WHEN @ControlKm=1 THEN 'S' ELSE 'N' END,@Observacion,@Usuario);SET @Id=SCOPE_IDENTITY();UPDATE flota.contrato SET Numero='ALQ-'+RIGHT('000000'+CONVERT(VARCHAR(6),@Id),6) WHERE Id_Contrato=@Id;SET @Mensaje='Contrato creado.';END
GO
IF OBJECT_ID('flota.p_dashboard','P') IS NOT NULL DROP PROCEDURE flota.p_dashboard;
GO
CREATE PROCEDURE flota.p_dashboard @id_empresa INT,@id_est CHAR(2),@Fecha DATE AS BEGIN SET NOCOUNT ON;SELECT c.Id_Contrato,c.Numero,v.Placa,ISNULL(v.MarcaTexto,'')+' '+ISNULL(v.ModeloTexto,'') Vehiculo,ISNULL(ch.Nombres,'') Chofer,c.Cod_Modalidad,m.Nombre Modalidad,c.FechaInicio,c.FechaFin,c.TarifaDia,c.Flg_ControlKm,ISNULL(td.Flg_Trabajo,'') Flg_TrabajoHoy,ISNULL(td.Cod_Motivo,'') MotivoHoy,ISNULL(td.ImporteGenerado,0) ImporteHoy,ISNULL(x.Deuda,0) TotalGenerado,ISNULL(x.Dias,0) DiasRegistrados,ISNULL(x.Km,0) KmAcumulado,ISNULL(x.Combustible,0) CombustibleAportado,ISNULL(x.Consumo,0) ConsumoEstimado FROM flota.contrato c JOIN flota.vehiculo v ON v.Id_Vehiculo=c.Id_Vehiculo JOIN flota.chofer ch ON ch.Id_Chofer=c.Id_Chofer JOIN flota.modalidad m ON m.Cod_Modalidad=c.Cod_Modalidad LEFT JOIN flota.operacion_dia td ON td.Id_Contrato=c.Id_Contrato AND td.Fecha=@Fecha OUTER APPLY(SELECT SUM(ImporteGenerado) Deuda,COUNT(*) Dias,SUM(ISNULL(KmRecorrido,0)) Km,SUM(ImporteCombustible) Combustible,SUM(CostoConsumoEstimado) Consumo FROM flota.operacion_dia z WHERE z.Id_Contrato=c.Id_Contrato)x WHERE c.id_empresa=@id_empresa AND c.id_est=@id_est AND c.Flg_Estado='A' AND c.FechaInicio<=@Fecha AND(c.FechaFin IS NULL OR c.FechaFin>=@Fecha) ORDER BY v.Placa;END
GO
IF OBJECT_ID('flota.p_trabajo_dia_guardar','P') IS NOT NULL DROP PROCEDURE flota.p_trabajo_dia_guardar;
GO
CREATE PROCEDURE flota.p_trabajo_dia_guardar @id_empresa INT,@id_est CHAR(2),@IdContrato INT,@Fecha DATE,@Trabajo BIT,@CodMotivo VARCHAR(3),@Cobrable BIT,@KmInicial DECIMAL(12,2)=NULL,@KmFinal DECIMAL(12,2)=NULL,@ImporteCombustible DECIMAL(18,2)=0,@Galones DECIMAL(12,3)=0,@PagoCombustible VARCHAR(1)=NULL,@Observacion VARCHAR(300)=NULL,@Usuario INT,@Id INT OUTPUT,@Mensaje VARCHAR(250) OUTPUT AS BEGIN SET NOCOUNT ON;SET @Id=0;DECLARE @Tarifa DECIMAL(18,2),@Modalidad VARCHAR(1),@Domingo VARCHAR(1),@ControlKm VARCHAR(1),@CostoKm DECIMAL(18,6);SELECT @Tarifa=c.TarifaDia,@Modalidad=c.Cod_Modalidad,@Domingo=c.Flg_CobraDomingo,@ControlKm=c.Flg_ControlKm,@CostoKm=CASE WHEN v.RendimientoTanqueKm>0 THEN(v.GalonesTanque*v.PrecioGalon)/v.RendimientoTanqueKm ELSE 0 END FROM flota.contrato c JOIN flota.vehiculo v ON v.Id_Vehiculo=c.Id_Vehiculo WHERE c.Id_Contrato=@IdContrato AND c.id_empresa=@id_empresa AND c.id_est=@id_est AND c.Flg_Estado='A';IF @Tarifa IS NULL BEGIN SET @Mensaje='Contrato activo no encontrado.';RETURN;END;IF @ControlKm='S' AND(@KmInicial IS NULL OR @KmFinal IS NULL OR @KmFinal<@KmInicial) BEGIN SET @Mensaje='Ingrese kilometraje inicial y final validos.';RETURN;END;DECLARE @EsDomingo BIT=CASE WHEN DATEDIFF(DAY,'19000107',@Fecha)%7=0 THEN 1 ELSE 0 END;DECLARE @Importe DECIMAL(18,2)=CASE WHEN @Cobrable=0 THEN 0 WHEN @Modalidad='L' AND @EsDomingo=1 AND @Domingo='N' THEN 0 WHEN @Modalidad='D' AND @Trabajo=0 THEN 0 ELSE @Tarifa END;DECLARE @Consumo DECIMAL(18,2)=ROUND(ISNULL(@KmFinal-@KmInicial,0)*ISNULL(@CostoKm,0),2);MERGE flota.operacion_dia AS t USING(SELECT @IdContrato Id,@Fecha Fecha)s ON t.Id_Contrato=s.Id AND t.Fecha=s.Fecha WHEN MATCHED THEN UPDATE SET Flg_Trabajo=CASE WHEN @Trabajo=1 THEN'S' ELSE'N' END,Cod_Motivo=@CodMotivo,Flg_Cobrable=CASE WHEN @Importe>0 THEN'S' ELSE'N' END,ImporteGenerado=@Importe,KmInicial=@KmInicial,KmFinal=@KmFinal,ImporteCombustible=@ImporteCombustible,GalonesCargados=@Galones,Flg_PagoCombustible=@PagoCombustible,CostoConsumoEstimado=@Consumo,Observacion=@Observacion,Usu_Modif=@Usuario,Fec_Modif=GETDATE() WHEN NOT MATCHED THEN INSERT(id_empresa,id_est,Id_Contrato,Fecha,Flg_Trabajo,Cod_Motivo,Flg_Cobrable,ImporteGenerado,KmInicial,KmFinal,ImporteCombustible,GalonesCargados,Flg_PagoCombustible,CostoConsumoEstimado,Observacion,Usu_Creacion)VALUES(@id_empresa,@id_est,@IdContrato,@Fecha,CASE WHEN @Trabajo=1 THEN'S' ELSE'N' END,@CodMotivo,CASE WHEN @Importe>0 THEN'S' ELSE'N' END,@Importe,@KmInicial,@KmFinal,@ImporteCombustible,@Galones,@PagoCombustible,@Consumo,@Observacion,@Usuario);SELECT @Id=Id_OperacionDia FROM flota.operacion_dia WHERE Id_Contrato=@IdContrato AND Fecha=@Fecha;SET @Mensaje='Dia registrado. Cargo generado: S/.'+CONVERT(VARCHAR(30),@Importe);END
GO
