using System.Security.Claims;using Aplicacion.Common;using Aplicacion.Interfaces;using Dominio.DTO.Flota;using GestionAlquileres.Security;using GestionAlquileres.ViewModels.Flota;using Microsoft.AspNetCore.Authentication;using Microsoft.AspNetCore.Mvc;using Microsoft.Extensions.Logging;
namespace GestionAlquileres.Controllers;
public class FlotaController:Controller
{readonly IFlotaService _s;readonly IWebHostEnvironment _env;readonly ILogger<FlotaController> _logger;public FlotaController(IFlotaService s,IWebHostEnvironment env,ILogger<FlotaController> logger){_s=s;_env=env;_logger=logger;}int Usuario()=>int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value,out var id)&&id>0?id:1007;
 static readonly string[] ExtPermitidas={".jpg",".jpeg",".png",".webp",".pdf"};const long MaxAdjuntoBytes=5_000_000;
 static readonly TimeZoneInfo PeruTimeZone=TimeZoneInfo.FindSystemTimeZoneById("SA Pacific Standard Time");
 static JsonResponseRequest<T> Fail<T>(string msg,T? data=default)=>new(){Success=false,Mensaje=msg,Data=data,Errors=new(){msg}};
 static string NormalizarTipoEntidad(string? tipo)=>(tipo??"").Trim().ToUpperInvariant();
 static string CarpetaAdjunto(string tipoEntidad)=>tipoEntidad=="PAGO_CONTRATO"?"pago-contrato":tipoEntidad=="RECIBO"?"recibo":tipoEntidad=="COMBUSTIBLE"?"combustible":"operacion-dia";
 static DateTime CombinarFechaConHoraActual(DateTime fecha){var ahora=DateTime.Now;return new DateTime(fecha.Year,fecha.Month,fecha.Day,ahora.Hour,ahora.Minute,ahora.Second);}
 static DateTime HoyPeru()=>TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow,PeruTimeZone).Date;
 static bool ArchivoPermitido(IFormFile? archivo,out string ext){ext=archivo==null?"":Path.GetExtension(archivo.FileName).ToLowerInvariant();return archivo is{Length:>0}&&archivo.Length<=MaxAdjuntoBytes&&ExtPermitidas.Contains(ext);}
 FlotaUsuarioMobileSesionDto? SesionMobile()=>FlotaMobileAuth.ReadSession(User);
 IActionResult JsonDenied(string msg,int statusCode=401)=>StatusCode(statusCode,new{success=false,message=msg,errors=new[]{msg}});
 IActionResult? ExigirSesionMobile(bool vista=false){if(SesionMobile()!=null)return null;return vista?RedirectToAction(nameof(MobileLogin)):JsonDenied("Inicia sesion mobile para continuar.");}
 async Task<bool> ContratoPermitidoMobileAsync(int idContrato,CancellationToken ct){var sesion=SesionMobile();if(sesion?.IdChofer is not >0||idContrato<=0)return false;var contratos=await _s.ListarContratosActivosPorChoferAsync(sesion.IdChofer.Value,ct);var lista=contratos.Data??new List<FlotaContratoAdminDto>();return contratos.Success&&lista.Any(x=>x.IdContrato==idContrato);}
 async Task<IActionResult?> ValidarContratoMobileAsync(int idContrato,CancellationToken ct){if(await ContratoPermitidoMobileAsync(idContrato,ct))return null;return JsonDenied("Tu sesion mobile no tiene acceso a ese contrato.",403);}
 async Task<List<FlotaContratoAdminDto>> ContratosActivosSesionMobileAsync(CancellationToken ct){var sesion=SesionMobile();if(sesion?.IdChofer is not >0)return new();var contratos=await _s.ListarContratosActivosPorChoferAsync(sesion.IdChofer.Value,ct);return contratos.Success?contratos.Data:new();}
 async Task<(FlotaContratoAdminDto? contrato,IActionResult? denied)> ResolverContratoSesionMobileAsync(int idContrato,CancellationToken ct){var contratos=await ContratosActivosSesionMobileAsync(ct);var contrato=contratos.FirstOrDefault(x=>x.IdContrato==idContrato);if(contrato==null)return (null,JsonDenied("Tu sesion mobile no tiene acceso a ese contrato.",403));return (contrato,null);}
 async Task<IActionResult> GuardarOperacionMobileInternaAsync(FlotaOperacionMobileGuardarDto x,string modo,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(x.IdContrato,ct);if(deny!=null)return deny;var hoyPeru=HoyPeru();if(x.Fecha.Date>hoyPeru)return Json(Fail("No puedes registrar una fecha posterior al dia actual en Peru.",new FlotaResultadoDto()));var sesion=SesionMobile();x.ModoRegistro=modo;x.FlgTrabajo="S";x.FlgCobrable="S";x.CodMotivo="TRA";if(modo=="I"){x.KmFinal=null;x.FechaHoraFin=null;x.FechaHoraInicio ??= CombinarFechaConHoraActual(x.Fecha);}else{x.FechaHoraFin ??= CombinarFechaConHoraActual(x.Fecha);}/* TODO: Administracion revisa/corrige estado final, cobrabilidad y motivo. */var result=await _s.GuardarOperacionMobileAsync(Usuario(),x,ct);if(sesion!=null&&result.Success)result.Mensaje="Registro enviado. Administracion podra revisar si corresponde cobrar o descontar.";return Json(result);}
 async Task<int?> ResolverContratoEntidadMobileAsync(string tipoEntidad,int idEntidad,CancellationToken ct){tipoEntidad=NormalizarTipoEntidad(tipoEntidad);return tipoEntidad switch{"OPERACION_DIA"=>await _s.ObtenerContratoPorOperacionDiaAsync(idEntidad,ct),"PAGO_CONTRATO"=>await _s.ObtenerContratoPorPagoContratoAsync(idEntidad,ct),"COMBUSTIBLE"=>await _s.ObtenerContratoPorCombustibleAsync(idEntidad,ct),_=>null};}
 [HttpGet]public IActionResult Index()=>View();[HttpGet]public async Task<IActionResult> Catalogos(CancellationToken ct)=>Json(await _s.CatalogosAsync(ct));[HttpGet]public async Task<IActionResult> Dashboard(DateTime? fecha,CancellationToken ct)=>Json(await _s.DashboardAsync(fecha??DateTime.Today,ct));
 [HttpGet]public IActionResult Contratos()=>View(new FlotaContratosViewModel());
 [HttpGet]public IActionResult DeudaChoferes()=>View(new FlotaDeudaChoferesViewModel());
 [HttpGet]public IActionResult UsuariosMobile()=>View(new FlotaUsuariosMobileViewModel());
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearVehiculo([FromBody]FlotaVehiculoCrearDto x,CancellationToken ct)=>Json(await _s.CrearVehiculoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearChofer([FromBody]FlotaChoferCrearDto x,CancellationToken ct)=>Json(await _s.CrearChoferAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearContrato([FromBody]FlotaContratoCrearDto x,CancellationToken ct)=>Json(await _s.CrearContratoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GuardarDia([FromBody]FlotaTrabajoDiaDto x,CancellationToken ct)=>Json(await _s.GuardarDiaAsync(Usuario(),x,ct));
 [HttpGet]public IActionResult AdminCalendario()=>View(new FlotaAdminCalendarioViewModel());
 [HttpGet]public async Task<IActionResult> ContratosAdmin(CancellationToken ct)=>Json(await _s.ContratosAdminAsync(ct));
 [HttpGet]public async Task<IActionResult> DeudaChoferesListar(int? idChofer,CancellationToken ct)=>Json(await _s.ListarDeudaChoferesAsync(idChofer,ct));
 [HttpGet]public async Task<IActionResult> ContratosListar(CancellationToken ct)=>Json(await _s.ContratosAdminAsync(ct));
 [HttpGet]public async Task<IActionResult> ContratoDetalle(int idContrato,CancellationToken ct)=>Json(await _s.ObtenerContratoDetalleAsync(idContrato,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> FinalizarContrato([FromBody]FlotaContratoFinalizarDto x,CancellationToken ct)=>Json(await _s.FinalizarContratoAsync(Usuario(),x,ct));
 [HttpGet]public async Task<IActionResult> UsuariosMobileListar(CancellationToken ct)=>Json(await _s.ListarUsuariosMobileAdminAsync(ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearUsuarioMobile([FromBody]FlotaUsuarioMobileCrearDto x,CancellationToken ct){try{return Json(await _s.CrearUsuarioMobileAsync(Usuario(),x,ct));}catch(Exception ex){return Json(Fail($"No se pudo crear el usuario mobile: {ex.Message}",new FlotaResultadoDto()));}}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ActualizarUsuarioMobile([FromBody]FlotaUsuarioMobileActualizarDto x,CancellationToken ct)=>Json(await _s.ActualizarUsuarioMobileAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CambiarEstadoUsuarioMobile([FromBody]FlotaUsuarioMobileCambiarEstadoDto x,CancellationToken ct)=>Json(await _s.CambiarEstadoUsuarioMobileAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public IActionResult CambiarContratoUsuarioMobile([FromBody]FlotaUsuarioMobileCambiarContratoDto x)=>Json(Fail("Operacion no disponible. Usuario mobile ya no maneja contrato fijo.",new FlotaResultadoDto()));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ResetPinUsuarioMobile([FromBody]FlotaUsuarioMobileResetPinDto x,CancellationToken ct)=>Json(await _s.ResetPinUsuarioMobileAsync(Usuario(),x,ct));
 [HttpGet]public async Task<IActionResult> ObtenerCalendario(int idContrato,int anio,int mes,CancellationToken ct)=>Json(await _s.CalendarioAsync(idContrato,anio,mes,ct));
 [HttpGet]public async Task<IActionResult> ListarRecibos(int idContrato,int? anio,int? mes,CancellationToken ct)=>Json(await _s.ListarRecibosAsync(idContrato,anio,mes,ct));
 [HttpGet]public async Task<IActionResult> ObtenerRecibo(int id,CancellationToken ct)=>Json(await _s.ObtenerReciboAsync(id,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GenerarRecibo([FromBody]FlotaReciboGenerarDto x,CancellationToken ct)=>Json(await _s.GenerarReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GenerarReciboManual([FromBody]FlotaReciboManualDto x,CancellationToken ct)=>Json(await _s.GenerarManualAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularRecibo([FromBody]FlotaReciboAnularDto x,CancellationToken ct)=>Json(await _s.AnularReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> QuitarDiaRecibo([FromBody]FlotaReciboQuitarDiaDto x,CancellationToken ct)=>Json(await _s.QuitarDiaReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditarPagoRecibo([FromBody]FlotaPagoReciboEditarDto x,CancellationToken ct)=>Json(await _s.EditarPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularPagoRecibo([FromBody]FlotaPagoReciboAnularDto x,CancellationToken ct)=>Json(await _s.AnularPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ValidarPagoRecibo([FromBody]FlotaPagoReciboValidarDto x,CancellationToken ct)=>Json(await _s.ValidarPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CorregirOperacionDia([FromBody]FlotaOperacionDiaCorregirDto x,CancellationToken ct)=>Json(await _s.CorregirOperacionDiaAsync(Usuario(),x,ct));
 [HttpGet]public IActionResult MobileLogin(){if(SesionMobile()!=null)return RedirectToAction(nameof(EstacionMobile));return View(new FlotaMobileLoginViewModel());}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileLogin([FromBody]FlotaMobileLoginDto x,CancellationToken ct){var telefono=(x.Telefono??"").Trim();var result=await _s.LoginMobileAsync(x,ct);if(!result.Success){_logger.LogWarning("Flota mobile login fallido. Telefono={Telefono} IsHttps={IsHttps} ForwardedProto={ForwardedProto} Mensaje={Mensaje}",telefono,Request.IsHttps,Request.Headers["X-Forwarded-Proto"].ToString(),result.Mensaje);return Json(result);}var sesion=result.Data??new FlotaUsuarioMobileSesionDto();await HttpContext.SignInAsync(FlotaMobileAuth.Scheme,FlotaMobileAuth.CreatePrincipal(sesion),new AuthenticationProperties{IsPersistent=true,AllowRefresh=true,ExpiresUtc=DateTimeOffset.UtcNow.AddDays(30)});_logger.LogInformation("Flota mobile login correcto. Telefono={Telefono} IdUsuarioMobile={IdUsuarioMobile} IdChofer={IdChofer} IsHttps={IsHttps} ForwardedProto={ForwardedProto} CookieSecurePolicy=SameAsRequest",telefono,sesion.IdUsuarioMobile,sesion.IdChofer,Request.IsHttps,Request.Headers["X-Forwarded-Proto"].ToString());return Json(new{success=true,message="Ingreso correcto.",data=new{redirectUrl=Url.Action(nameof(EstacionMobile),"Flota"),sesion}});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileLogout(){await HttpContext.SignOutAsync(FlotaMobileAuth.Scheme);return Json(new{success=true,message="Sesion cerrada.",data=new{redirectUrl=Url.Action(nameof(MobileLogin),"Flota")}});}
 // TODO: No exponer endpoints mobile publicamente sin login/sesion/PIN/token real.
 [HttpGet]public async Task<IActionResult> EstacionMobile(CancellationToken ct){var deny=ExigirSesionMobile(true);if(deny!=null)return deny;var sesion=SesionMobile();var hoyPeru=HoyPeru();var contratos=await ContratosActivosSesionMobileAsync(ct);var idAuto=contratos.Count==1?contratos[0].IdContrato:(int?)null;return View(new FlotaEstacionMobileViewModel{FechaOperacionInicial=hoyPeru,FechaOperacionMaxima=hoyPeru,EsSesionMobile=sesion!=null,NombreSesion=sesion?.Nombre??"",TelefonoSesion=sesion?.Telefono??"",IdContratoAsignado=idAuto,PuedeCambiarContrato=contratos.Count>1,PuedeOperar=contratos.Count>0,MensajeContrato=contratos.Count switch{0=>"No tiene contrato activo asignado. Comuniquese con administracion.",1=>"",_=>"Se encontraron varios contratos activos para tu chofer. Selecciona el correcto para operar."},TabInicial="intervalos"});}
 [HttpGet]public async Task<IActionResult> EstacionMobileContratos(CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var contratos=await ContratosActivosSesionMobileAsync(ct);return Json(new JsonResponseRequest<FlotaEstacionMobileDto>{Success=true,Mensaje="",Data=new FlotaEstacionMobileDto{Contratos=contratos,FechaOperacion=HoyPeru()}});}
 [HttpGet]public async Task<IActionResult> MobileResumenGlobal(CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var sesion=SesionMobile();if(sesion?.IdChofer is not >0)return Json(Fail("No se pudo identificar el chofer mobile.",new FlotaChoferResumenGlobalMobileDto()));return Json(await _s.ObtenerResumenGlobalMobileAsync(sesion.IdChofer.Value,ct));}
 [HttpGet]public async Task<IActionResult> MobileDetalleDeudaGlobal(CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var sesion=SesionMobile();if(sesion?.IdChofer is not >0)return Json(Fail("No se pudo identificar el chofer mobile.",new FlotaChoferDetalleGlobalMobileDto()));return Json(await _s.ObtenerDetalleGlobalMobileAsync(sesion.IdChofer.Value,ct));}
 [HttpGet]public async Task<IActionResult> OperacionMobileDetalle(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(idContrato,ct);if(deny!=null)return deny;var hoyPeru=HoyPeru();var fechaConsulta=(fecha??hoyPeru).Date;if(fechaConsulta>hoyPeru)fechaConsulta=hoyPeru;return Json(await _s.ObtenerOperacionMobileAsync(new FlotaOperacionMobileConsultaDto{IdContrato=idContrato,Fecha=fechaConsulta},ct));}
 [HttpGet]public async Task<IActionResult> MobileIntervalosDia(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var hoyPeru=HoyPeru();var fechaOperativa=(fecha??hoyPeru).Date;if(fechaOperativa>hoyPeru)fechaOperativa=hoyPeru;var resolved=await ResolverContratoSesionMobileAsync(idContrato,ct);if(resolved.denied!=null)return resolved.denied;var contrato=resolved.contrato!;return Json(await _s.ListarIntervalosDiaMobileAsync(contrato.IdContrato,contrato.IdChofer,contrato.IdVehiculo,fechaOperativa,ct));}
 [HttpGet]public async Task<IActionResult> MobileResumenHorasDia(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var hoyPeru=HoyPeru();var fechaOperativa=(fecha??hoyPeru).Date;if(fechaOperativa>hoyPeru)fechaOperativa=hoyPeru;var resolved=await ResolverContratoSesionMobileAsync(idContrato,ct);if(resolved.denied!=null)return resolved.denied;var contrato=resolved.contrato!;return Json(await _s.ObtenerResumenHorasMobileAsync(contrato.IdContrato,contrato.IdChofer,contrato.IdVehiculo,fechaOperativa,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileIntervaloAbrir([FromBody]FlotaIntervaloAbrirRequestDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var resolved=await ResolverContratoSesionMobileAsync(x.IdContrato,ct);if(resolved.denied!=null)return resolved.denied;var contrato=resolved.contrato!;if(x.FechaHoraInicio>DateTime.Now.AddMinutes(1))return Json(Fail("No puedes registrar un inicio futuro.",new FlotaResultadoDto()));x.IdChofer=contrato.IdChofer;x.IdVehiculo=contrato.IdVehiculo;var result=await _s.AbrirIntervaloMobileAsync(Usuario(),x,ct);if(result.Success)result.Mensaje="Intervalo iniciado. Administracion podra revisar el uso registrado.";return Json(result);}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileIntervaloCerrar([FromBody]FlotaIntervaloCerrarRequestDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var resolved=await ResolverContratoSesionMobileAsync(x.IdContrato,ct);if(resolved.denied!=null)return resolved.denied;var contrato=resolved.contrato!;if(x.FechaHoraFin>DateTime.Now.AddMinutes(1))return Json(Fail("No puedes registrar un cierre futuro.",new FlotaResultadoDto()));x.IdChofer=contrato.IdChofer;x.IdVehiculo=contrato.IdVehiculo;var result=await _s.CerrarIntervaloMobileAsync(Usuario(),x,ct);if(result.Success)result.Mensaje="Intervalo cerrado. Administracion podra revisar el estado final del dia.";return Json(result);}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileIntervaloAnular([FromBody]FlotaIntervaloAnularRequestDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(x.IdContrato,ct);if(deny!=null)return deny;return Json(await _s.AnularIntervaloMobileAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public Task<IActionResult> GuardarInicioOperacionMobile([FromBody]FlotaOperacionMobileGuardarDto x,CancellationToken ct)=>GuardarOperacionMobileInternaAsync(x,"I",ct);
 [HttpPost][ValidateAntiForgeryToken]public Task<IActionResult> GuardarFinOperacionMobile([FromBody]FlotaOperacionMobileGuardarDto x,CancellationToken ct)=>GuardarOperacionMobileInternaAsync(x,"F",ct);
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GuardarOperacionMobile([FromBody]FlotaOperacionMobileGuardarDto x,CancellationToken ct){var modo=(x.ModoRegistro??"").Trim().ToUpperInvariant();modo=modo=="F"?"F":"I";return await GuardarOperacionMobileInternaAsync(x,modo,ct);}
 [HttpGet]public async Task<IActionResult> CombustiblesPorFecha(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(idContrato,ct);if(deny!=null)return deny;var hoyPeru=HoyPeru();var fechaConsulta=(fecha??hoyPeru).Date;if(fechaConsulta>hoyPeru)fechaConsulta=hoyPeru;return Json(await _s.ListarCombustiblePorContratoFechaAsync(idContrato,fechaConsulta,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> RegistrarCombustible([FromBody]FlotaCombustibleRegistrarDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(x.IdContrato,ct);if(deny!=null)return deny;if(x.Fecha.Date>HoyPeru())return Json(Fail("No puedes registrar combustible con una fecha posterior al dia actual en Peru.",new FlotaResultadoDto()));return Json(await _s.RegistrarCombustibleOperacionAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularCombustible([FromBody]FlotaCombustibleAnularDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var idContrato=await _s.ObtenerContratoPorCombustibleAsync(x.IdCombustibleOperacion,ct);if(!idContrato.HasValue)return JsonDenied("Carga de combustible no encontrada.",404);deny=await ValidarContratoMobileAsync(idContrato.Value,ct);if(deny!=null)return deny;return Json(await _s.AnularCombustibleOperacionAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> RegistrarPagoContrato([FromBody]FlotaPagoContratoRegistrarDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(x.IdContrato,ct);if(deny!=null)return deny;if(x.FechaPago.Date>HoyPeru())return Json(Fail("No puedes registrar un pago con una fecha posterior al dia actual en Peru.",new FlotaResultadoDto()));return Json(await _s.RegistrarPagoContratoAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditarPagoContratoMobile([FromBody]FlotaPagoContratoEditarMobileDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var idContrato=await _s.ObtenerContratoPorPagoContratoAsync(x.IdPagoContrato,ct);if(!idContrato.HasValue)return JsonDenied("Pago declarado no encontrado.",404);deny=await ValidarContratoMobileAsync(idContrato.Value,ct);if(deny!=null)return deny;if(x.FechaPago.Date>HoyPeru())return Json(Fail("No puedes registrar un pago con una fecha posterior al dia actual en Peru.",new FlotaResultadoDto()));return Json(await _s.EditarPagoContratoMobileAsync(Usuario(),x,ct));}
 [HttpGet]public async Task<IActionResult> PagoContratoDetalle(int idPagoContrato,CancellationToken ct){var sesion=SesionMobile();if(sesion!=null){var idContrato=await _s.ObtenerContratoPorPagoContratoAsync(idPagoContrato,ct);if(!idContrato.HasValue)return JsonDenied("Pago declarado no encontrado.",404);var deny=await ValidarContratoMobileAsync(idContrato.Value,ct);if(deny!=null)return deny;}return Json(await _s.ObtenerPagoContratoAsync(idPagoContrato,ct));}
 [HttpGet]public async Task<IActionResult> PagosContratoPendientes(int? idContrato,DateTime? fechaDesde,DateTime? fechaHasta,string? texto,CancellationToken ct)=>Json(await _s.ListarPagosContratoPendientesAsync(idContrato,fechaDesde,fechaHasta,texto,ct));
 [HttpGet]public async Task<IActionResult> PagosContratoPorContrato(int idContrato,string? flgValidado,string? flgEstado,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=await ValidarContratoMobileAsync(idContrato,ct);if(deny!=null)return deny;return Json(await _s.ListarPagosContratoPorContratoAsync(idContrato,flgValidado,flgEstado,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ValidarPagoContrato([FromBody]FlotaPagoContratoValidarDto x,CancellationToken ct)=>Json(await _s.ValidarPagoContratoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularPagoContrato([FromBody]FlotaPagoContratoAnularDto x,CancellationToken ct)=>Json(await _s.AnularPagoContratoAsync(Usuario(),x,ct));
 [HttpGet]public async Task<IActionResult> AdjuntosFlota(string tipoEntidad,int idEntidad,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var sesion=SesionMobile();if(sesion!=null){var idContrato=await ResolverContratoEntidadMobileAsync(tipoEntidad,idEntidad,ct);if(!idContrato.HasValue)return JsonDenied("Adjunto o entidad no permitida para mobile.",403);deny=await ValidarContratoMobileAsync(idContrato.Value,ct);if(deny!=null)return deny;}return Json(await _s.ListarAdjuntosFlotaAsync(tipoEntidad,idEntidad,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularAdjuntoFlota([FromBody]FlotaAdjuntoAnularDto x,CancellationToken ct)=>Json(await _s.AnularAdjuntoFlotaAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(6_000_000)]public async Task<IActionResult> SubirAdjuntoFlota([FromForm]FlotaAdjuntoRegistrarDto x,IFormFile? archivo,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;x.TipoEntidad=NormalizarTipoEntidad(x.TipoEntidad);var sesion=SesionMobile();if(sesion!=null){var idContrato=await ResolverContratoEntidadMobileAsync(x.TipoEntidad,x.IdEntidad,ct);if(!idContrato.HasValue)return JsonDenied("No puedes adjuntar archivos a esa entidad.",403);deny=await ValidarContratoMobileAsync(idContrato.Value,ct);if(deny!=null)return deny;}if(archivo is null||archivo.Length<=0)return Json(Fail("Selecciona un archivo.",new FlotaResultadoDto()));if(!ArchivoPermitido(archivo,out var ext))return Json(Fail("Archivo invalido. Usa JPG, PNG, WEBP o PDF de hasta 5 MB.",new FlotaResultadoDto()));var carpeta=CarpetaAdjunto(x.TipoEntidad);var dir=Path.Combine(_env.WebRootPath,"uploads","flota",carpeta);Directory.CreateDirectory(dir);var name=$"{carpeta}_{Guid.NewGuid():N}{ext}";var fullPath=Path.Combine(dir,name);var relativePath=$"/uploads/flota/{carpeta}/{name}";try{await using(var fs=System.IO.File.Create(fullPath)){await archivo.CopyToAsync(fs,ct);}x.RutaArchivo=relativePath;x.NombreOriginal=Path.GetFileName(archivo.FileName);x.MimeType=string.IsNullOrWhiteSpace(archivo.ContentType)?null:archivo.ContentType;x.TamanoBytes=archivo.Length;var result=await _s.RegistrarAdjuntoFlotaAsync(Usuario(),x,ct);if(!result.Success&&System.IO.File.Exists(fullPath))System.IO.File.Delete(fullPath);return Json(result);}catch(Exception ex){if(System.IO.File.Exists(fullPath))System.IO.File.Delete(fullPath);return Json(Fail($"No se pudo registrar el adjunto. {ex.Message}",new FlotaResultadoDto()));}}
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(6_000_000)]public async Task<IActionResult> RegistrarPago([FromForm]FlotaPagoReciboDto x,IFormFile? voucher,CancellationToken ct){if(voucher is{Length:>0}){var ext=Path.GetExtension(voucher.FileName).ToLowerInvariant();if(voucher.Length>5_000_000||!new[]{".jpg",".jpeg",".png",".webp",".pdf"}.Contains(ext))return BadRequest(new{success=false,message="Voucher invalido. Usa imagen o PDF de hasta 5 MB."});var dir=Path.Combine(_env.WebRootPath,"uploads","flota","vouchers");Directory.CreateDirectory(dir);var name=$"voucher_{DateTime.Now:yyyyMMddHHmmss}_{Guid.NewGuid():N}{ext}";await using var fs=System.IO.File.Create(Path.Combine(dir,name));await voucher.CopyToAsync(fs,ct);x.FotoVoucher=$"/uploads/flota/vouchers/{name}";}return Json(await _s.RegistrarPagoAsync(Usuario(),x,ct));}
}
