using System.Security.Claims;using Aplicacion.Common;using Aplicacion.Interfaces;using Dominio.DTO.Flota;using GestionAlquileres.Security;using GestionAlquileres.ViewModels.Flota;using Microsoft.AspNetCore.Authentication;using Microsoft.AspNetCore.Mvc;
namespace GestionAlquileres.Controllers;
public class FlotaController:Controller
{readonly IFlotaService _s;readonly IWebHostEnvironment _env;public FlotaController(IFlotaService s,IWebHostEnvironment env){_s=s;_env=env;}int Usuario()=>int.TryParse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value,out var id)&&id>0?id:1007;
 static readonly string[] ExtPermitidas={".jpg",".jpeg",".png",".webp",".pdf"};const long MaxAdjuntoBytes=5_000_000;
 static JsonResponseRequest<T> Fail<T>(string msg,T? data=default)=>new(){Success=false,Mensaje=msg,Data=data,Errors=new(){msg}};
 static string NormalizarTipoEntidad(string? tipo)=>(tipo??"").Trim().ToUpperInvariant();
 static string CarpetaAdjunto(string tipoEntidad)=>tipoEntidad=="PAGO_CONTRATO"?"pago-contrato":tipoEntidad=="RECIBO"?"recibo":tipoEntidad=="COMBUSTIBLE"?"combustible":"operacion-dia";
 static bool ArchivoPermitido(IFormFile? archivo,out string ext){ext=archivo==null?"":Path.GetExtension(archivo.FileName).ToLowerInvariant();return archivo is{Length:>0}&&archivo.Length<=MaxAdjuntoBytes&&ExtPermitidas.Contains(ext);}
 FlotaUsuarioMobileSesionDto? SesionMobile()=>FlotaMobileAuth.ReadSession(User);
 IActionResult JsonDenied(string msg,int statusCode=401)=>StatusCode(statusCode,new{success=false,message=msg,errors=new[]{msg}});
 IActionResult? ExigirSesionMobile(bool vista=false){if(SesionMobile()!=null)return null;return vista?RedirectToAction(nameof(MobileLogin)):JsonDenied("Inicia sesion mobile para continuar.");}
 IActionResult? ValidarContratoMobile(int idContrato){var sesion=SesionMobile();if(sesion?.IdContrato is >0 && sesion.IdContrato.Value!=idContrato)return JsonDenied("Tu sesion mobile no tiene acceso a ese contrato.",403);return null;}
 async Task<int?> ResolverContratoEntidadMobileAsync(string tipoEntidad,int idEntidad,CancellationToken ct){tipoEntidad=NormalizarTipoEntidad(tipoEntidad);return tipoEntidad switch{"OPERACION_DIA"=>await _s.ObtenerContratoPorOperacionDiaAsync(idEntidad,ct),"PAGO_CONTRATO"=>await _s.ObtenerContratoPorPagoContratoAsync(idEntidad,ct),"COMBUSTIBLE"=>await _s.ObtenerContratoPorCombustibleAsync(idEntidad,ct),_=>null};}
 [HttpGet]public IActionResult Index()=>View();[HttpGet]public async Task<IActionResult> Catalogos(CancellationToken ct)=>Json(await _s.CatalogosAsync(ct));[HttpGet]public async Task<IActionResult> Dashboard(DateTime? fecha,CancellationToken ct)=>Json(await _s.DashboardAsync(fecha??DateTime.Today,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearVehiculo([FromBody]FlotaVehiculoCrearDto x,CancellationToken ct)=>Json(await _s.CrearVehiculoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearChofer([FromBody]FlotaChoferCrearDto x,CancellationToken ct)=>Json(await _s.CrearChoferAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CrearContrato([FromBody]FlotaContratoCrearDto x,CancellationToken ct)=>Json(await _s.CrearContratoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GuardarDia([FromBody]FlotaTrabajoDiaDto x,CancellationToken ct)=>Json(await _s.GuardarDiaAsync(Usuario(),x,ct));
 [HttpGet]public IActionResult AdminCalendario()=>View(new FlotaAdminCalendarioViewModel());
 [HttpGet]public async Task<IActionResult> ContratosAdmin(CancellationToken ct)=>Json(await _s.ContratosAdminAsync(ct));
 [HttpGet]public async Task<IActionResult> ObtenerCalendario(int idContrato,int anio,int mes,CancellationToken ct)=>Json(await _s.CalendarioAsync(idContrato,anio,mes,ct));
 [HttpGet]public async Task<IActionResult> ListarRecibos(int idContrato,int? anio,int? mes,CancellationToken ct)=>Json(await _s.ListarRecibosAsync(idContrato,anio,mes,ct));
 [HttpGet]public async Task<IActionResult> ObtenerRecibo(int id,CancellationToken ct)=>Json(await _s.ObtenerReciboAsync(id,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GenerarRecibo([FromBody]FlotaReciboGenerarDto x,CancellationToken ct)=>Json(await _s.GenerarReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GenerarReciboManual([FromBody]FlotaReciboManualDto x,CancellationToken ct)=>Json(await _s.GenerarManualAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularRecibo([FromBody]FlotaReciboAnularDto x,CancellationToken ct)=>Json(await _s.AnularReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> QuitarDiaRecibo([FromBody]FlotaReciboQuitarDiaDto x,CancellationToken ct)=>Json(await _s.QuitarDiaReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> EditarPagoRecibo([FromBody]FlotaPagoReciboEditarDto x,CancellationToken ct)=>Json(await _s.EditarPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularPagoRecibo([FromBody]FlotaPagoReciboAnularDto x,CancellationToken ct)=>Json(await _s.AnularPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ValidarPagoRecibo([FromBody]FlotaPagoReciboValidarDto x,CancellationToken ct)=>Json(await _s.ValidarPagoReciboAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> CorregirOperacionDia([FromBody]FlotaOperacionDiaCorregirDto x,CancellationToken ct)=>Json(await _s.CorregirOperacionDiaAsync(Usuario(),x,ct));
 [HttpGet]public IActionResult MobileLogin(){if(SesionMobile()!=null)return RedirectToAction(nameof(EstacionMobile));return View(new FlotaMobileLoginViewModel());}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileLogin([FromBody]FlotaMobileLoginDto x,CancellationToken ct){var result=await _s.LoginMobileAsync(x,ct);if(!result.Success)return Json(result);var sesion=result.Data??new FlotaUsuarioMobileSesionDto();await HttpContext.SignInAsync(FlotaMobileAuth.Scheme,FlotaMobileAuth.CreatePrincipal(sesion),new AuthenticationProperties{IsPersistent=true,AllowRefresh=true,ExpiresUtc=DateTimeOffset.UtcNow.AddDays(30)});return Json(new{success=true,message="Ingreso correcto.",data=new{redirectUrl=Url.Action(nameof(EstacionMobile),"Flota"),sesion}});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> MobileLogout(){await HttpContext.SignOutAsync(FlotaMobileAuth.Scheme);return Json(new{success=true,message="Sesion cerrada.",data=new{redirectUrl=Url.Action(nameof(MobileLogin),"Flota")}});}
 // TODO: No exponer endpoints mobile publicamente sin login/sesion/PIN/token real.
 [HttpGet]public IActionResult EstacionMobile(){var deny=ExigirSesionMobile(true);if(deny!=null)return deny;var sesion=SesionMobile();return View(new FlotaEstacionMobileViewModel{FechaOperacionInicial=DateTime.Today,EsSesionMobile=sesion!=null,NombreSesion=sesion?.Nombre??"",TelefonoSesion=sesion?.Telefono??"",IdContratoAsignado=sesion?.IdContrato,PuedeCambiarContrato=!(sesion?.IdContrato is >0)});}
 [HttpGet]public async Task<IActionResult> EstacionMobileContratos(CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var r=await _s.EstacionMobileAsync(ct);var sesion=SesionMobile();if(r.Success&&sesion?.IdContrato is >0&&r.Data!=null)r.Data.Contratos=r.Data.Contratos.Where(x=>x.IdContrato==sesion.IdContrato.Value).ToList();return Json(r);}
 [HttpGet]public async Task<IActionResult> OperacionMobileDetalle(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(idContrato);if(deny!=null)return deny;return Json(await _s.ObtenerOperacionMobileAsync(new FlotaOperacionMobileConsultaDto{IdContrato=idContrato,Fecha=fecha??DateTime.Today},ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> GuardarOperacionMobile([FromBody]FlotaOperacionMobileGuardarDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(x.IdContrato);if(deny!=null)return deny;var sesion=SesionMobile();if(sesion!=null){x.FlgTrabajo=(x.FlgTrabajo??"").Trim().ToUpperInvariant();x.FlgCobrable=x.FlgTrabajo=="S"?"S":"N";/* TODO: Cobrable final debe ser confirmado por administracion. */}var result=await _s.GuardarOperacionMobileAsync(Usuario(),x,ct);if(sesion!=null&&result.Success)result.Mensaje="Registro enviado. Administracion podra revisar si corresponde cobrar o descontar.";return Json(result);}
 [HttpGet]public async Task<IActionResult> CombustiblesPorFecha(int idContrato,DateTime? fecha,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(idContrato);if(deny!=null)return deny;return Json(await _s.ListarCombustiblePorContratoFechaAsync(idContrato,fecha??DateTime.Today,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> RegistrarCombustible([FromBody]FlotaCombustibleRegistrarDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(x.IdContrato);if(deny!=null)return deny;return Json(await _s.RegistrarCombustibleOperacionAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularCombustible([FromBody]FlotaCombustibleAnularDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var idContrato=await _s.ObtenerContratoPorCombustibleAsync(x.IdCombustibleOperacion,ct);if(!idContrato.HasValue)return JsonDenied("Carga de combustible no encontrada.",404);deny=ValidarContratoMobile(idContrato.Value);if(deny!=null)return deny;return Json(await _s.AnularCombustibleOperacionAsync(Usuario(),x,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> RegistrarPagoContrato([FromBody]FlotaPagoContratoRegistrarDto x,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(x.IdContrato);if(deny!=null)return deny;return Json(await _s.RegistrarPagoContratoAsync(Usuario(),x,ct));}
 [HttpGet]public async Task<IActionResult> PagoContratoDetalle(int idPagoContrato,CancellationToken ct){var sesion=SesionMobile();if(sesion!=null){var idContrato=await _s.ObtenerContratoPorPagoContratoAsync(idPagoContrato,ct);if(!idContrato.HasValue)return JsonDenied("Pago declarado no encontrado.",404);var deny=ValidarContratoMobile(idContrato.Value);if(deny!=null)return deny;}return Json(await _s.ObtenerPagoContratoAsync(idPagoContrato,ct));}
 [HttpGet]public async Task<IActionResult> PagosContratoPendientes(int? idContrato,DateTime? fechaDesde,DateTime? fechaHasta,string? texto,CancellationToken ct)=>Json(await _s.ListarPagosContratoPendientesAsync(idContrato,fechaDesde,fechaHasta,texto,ct));
 [HttpGet]public async Task<IActionResult> PagosContratoPorContrato(int idContrato,string? flgValidado,string? flgEstado,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;deny=ValidarContratoMobile(idContrato);if(deny!=null)return deny;return Json(await _s.ListarPagosContratoPorContratoAsync(idContrato,flgValidado,flgEstado,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> ValidarPagoContrato([FromBody]FlotaPagoContratoValidarDto x,CancellationToken ct)=>Json(await _s.ValidarPagoContratoAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularPagoContrato([FromBody]FlotaPagoContratoAnularDto x,CancellationToken ct)=>Json(await _s.AnularPagoContratoAsync(Usuario(),x,ct));
 [HttpGet]public async Task<IActionResult> AdjuntosFlota(string tipoEntidad,int idEntidad,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;var sesion=SesionMobile();if(sesion!=null){var idContrato=await ResolverContratoEntidadMobileAsync(tipoEntidad,idEntidad,ct);if(!idContrato.HasValue)return JsonDenied("Adjunto o entidad no permitida para mobile.",403);deny=ValidarContratoMobile(idContrato.Value);if(deny!=null)return deny;}return Json(await _s.ListarAdjuntosFlotaAsync(tipoEntidad,idEntidad,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult> AnularAdjuntoFlota([FromBody]FlotaAdjuntoAnularDto x,CancellationToken ct)=>Json(await _s.AnularAdjuntoFlotaAsync(Usuario(),x,ct));
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(6_000_000)]public async Task<IActionResult> SubirAdjuntoFlota([FromForm]FlotaAdjuntoRegistrarDto x,IFormFile? archivo,CancellationToken ct){var deny=ExigirSesionMobile();if(deny!=null)return deny;x.TipoEntidad=NormalizarTipoEntidad(x.TipoEntidad);var sesion=SesionMobile();if(sesion!=null){var idContrato=await ResolverContratoEntidadMobileAsync(x.TipoEntidad,x.IdEntidad,ct);if(!idContrato.HasValue)return JsonDenied("No puedes adjuntar archivos a esa entidad.",403);deny=ValidarContratoMobile(idContrato.Value);if(deny!=null)return deny;}if(archivo is null||archivo.Length<=0)return Json(Fail("Selecciona un archivo.",new FlotaResultadoDto()));if(!ArchivoPermitido(archivo,out var ext))return Json(Fail("Archivo invalido. Usa JPG, PNG, WEBP o PDF de hasta 5 MB.",new FlotaResultadoDto()));var carpeta=CarpetaAdjunto(x.TipoEntidad);var dir=Path.Combine(_env.WebRootPath,"uploads","flota",carpeta);Directory.CreateDirectory(dir);var name=$"{carpeta}_{Guid.NewGuid():N}{ext}";var fullPath=Path.Combine(dir,name);var relativePath=$"/uploads/flota/{carpeta}/{name}";try{await using(var fs=System.IO.File.Create(fullPath)){await archivo.CopyToAsync(fs,ct);}x.RutaArchivo=relativePath;x.NombreOriginal=Path.GetFileName(archivo.FileName);x.MimeType=string.IsNullOrWhiteSpace(archivo.ContentType)?null:archivo.ContentType;x.TamanoBytes=archivo.Length;var result=await _s.RegistrarAdjuntoFlotaAsync(Usuario(),x,ct);if(!result.Success&&System.IO.File.Exists(fullPath))System.IO.File.Delete(fullPath);return Json(result);}catch(Exception ex){if(System.IO.File.Exists(fullPath))System.IO.File.Delete(fullPath);return Json(Fail($"No se pudo registrar el adjunto. {ex.Message}",new FlotaResultadoDto()));}}
 [HttpPost][ValidateAntiForgeryToken][RequestSizeLimit(6_000_000)]public async Task<IActionResult> RegistrarPago([FromForm]FlotaPagoReciboDto x,IFormFile? voucher,CancellationToken ct){if(voucher is{Length:>0}){var ext=Path.GetExtension(voucher.FileName).ToLowerInvariant();if(voucher.Length>5_000_000||!new[]{".jpg",".jpeg",".png",".webp",".pdf"}.Contains(ext))return BadRequest(new{success=false,message="Voucher invalido. Usa imagen o PDF de hasta 5 MB."});var dir=Path.Combine(_env.WebRootPath,"uploads","flota","vouchers");Directory.CreateDirectory(dir);var name=$"voucher_{DateTime.Now:yyyyMMddHHmmss}_{Guid.NewGuid():N}{ext}";await using var fs=System.IO.File.Create(Path.Combine(dir,name));await voucher.CopyToAsync(fs,ct);x.FotoVoucher=$"/uploads/flota/vouchers/{name}";}return Json(await _s.RegistrarPagoAsync(Usuario(),x,ct));}
}
