using System.Data;
using Dominio.DTO.Compensacion;
using Infraestructura.Data;
using Infraestructura.Interfaces;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Options;
namespace Infraestructura.Repositorio;
public class CompensacionRepository:ClsConexion,ICompensacionRepository
{
 public CompensacionRepository(IOptions<SqlConfig> config):base(config){}
 private SqlCommand Cmd(SqlConnection c,string name)=>new(name,c){CommandType=CommandType.StoredProcedure};
 public async Task<List<CompensacionConceptoDto>> CatalogosAsync(CancellationToken ct){var a=new List<CompensacionConceptoDto>();await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_catalogos");await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))a.Add(new(){Codigo=S(r,"Cod_Concepto"),Nombre=S(r,"Nombre")});return a;}
 public async Task<CompensacionResultadoDto> CrearObligacionAsync(int e,string est,int u,CompensacionObligacionCrearDto x,CancellationToken ct){await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_obligacion_crear");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@Cod_TipAnex",x.CodTipAnex);m.Parameters.AddWithValue("@Cod_Anxo",x.CodAnxo);m.Parameters.AddWithValue("@Cod_Concepto",x.CodConcepto);m.Parameters.AddWithValue("@Fecha",x.Fecha);m.Parameters.AddWithValue("@Importe",x.Importe);m.Parameters.AddWithValue("@Referencia",(object?)x.Referencia??DBNull.Value);m.Parameters.AddWithValue("@Observacion",(object?)x.Observacion??DBNull.Value);m.Parameters.AddWithValue("@Usuario",u);var (ok,msg,id)=Out(m,true);await c.OpenAsync(ct);await m.ExecuteNonQueryAsync(ct);return Result(ok,msg,id);}
 public async Task<List<CompensacionObligacionDto>> ObligacionesAsync(int e,string est,string t,string a,CancellationToken ct){var l=new List<CompensacionObligacionDto>();await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_obligacion_listar");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@Cod_TipAnex",t);m.Parameters.AddWithValue("@Cod_Anxo",a);await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))l.Add(new(){IdObligacion=I(r,"Id_Obligacion"),Fecha=DT(r,"Fecha"),Persona=S(r,"Persona"),Concepto=S(r,"Concepto"),Importe=D(r,"Importe"),ImporteAplicado=D(r,"ImporteAplicado"),SaldoDisponible=D(r,"SaldoDisponible"),Referencia=S(r,"Referencia"),Estado=S(r,"Flg_Estado")});return l;}
 public async Task<List<CompensacionPrestamoDto>> PrestamosAsync(int e,string t,string a,DateTime f,CancellationToken ct){var l=new List<CompensacionPrestamoDto>();await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_prestamos_cliente");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@Cod_TipAnex",t);m.Parameters.AddWithValue("@Cod_Anxo",a);m.Parameters.AddWithValue("@FechaCorte",f);await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))l.Add(new(){IdPrestamo=I(r,"Id_Prestamo"),Fecha=DT(r,"Fecha"),FechaFinCobro=DT(r,"FechaFinCobro"),Concepto=S(r,"Concepto"),SaldoPendiente=D(r,"SaldoPendiente"),SaldoVencido=D(r,"SaldoVencido"),CuotasVencidas=I(r,"CuotasVencidas")});return l;}
 public async Task<CompensacionSimulacionDto?> SimularAsync(int e,string est,CompensacionSimularRequestDto x,CancellationToken ct){await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_simular");AddBase(m,e,est,x);await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct)||!Convert.ToBoolean(r["Ok"]))return null;var d=new CompensacionSimulacionDto{SaldoFavorAntes=D(r,"SaldoFavorAntes"),ImporteSolicitado=D(r,"ImporteSolicitado"),ImporteAplicado=D(r,"ImporteAplicado"),SaldoFavorDespues=D(r,"SaldoFavorDespues"),InteresAplicado=D(r,"InteresAplicado"),CapitalAplicado=D(r,"CapitalAplicado"),CuotasAfectadas=I(r,"CuotasAfectadas")};if(await r.NextResultAsync(ct))while(await r.ReadAsync(ct))d.Detalle.Add(MapDetalle(r));return d;}
 public async Task<CompensacionResultadoDto> AplicarAsync(int e,string est,int u,CompensacionAplicarRequestDto x,CancellationToken ct){await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_aplicar");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@Cod_TipAnex",x.CodTipAnex);m.Parameters.AddWithValue("@Cod_Anxo",x.CodAnxo);m.Parameters.AddWithValue("@Id_Obligacion",x.IdObligacion);m.Parameters.AddWithValue("@IdsPrestamo",string.Join(',',x.IdsPrestamo));m.Parameters.AddWithValue("@Fecha",x.FechaCorte);m.Parameters.AddWithValue("@Importe",x.Importe);m.Parameters.AddWithValue("@SoloVencidas",x.SoloVencidas);m.Parameters.AddWithValue("@Motivo",x.Motivo);m.Parameters.AddWithValue("@Observacion",(object?)x.Observacion??DBNull.Value);m.Parameters.AddWithValue("@Usuario",u);var(ok,msg,id)=Out(m,true,"@IdCompensacion");await c.OpenAsync(ct);await m.ExecuteNonQueryAsync(ct);return Result(ok,msg,id);}
 public async Task<CompensacionResultadoDto> RevertirAsync(int e,string est,int u,CompensacionRevertirDto x,CancellationToken ct){await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_revertir");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@IdCompensacion",x.IdCompensacion);m.Parameters.AddWithValue("@Motivo",x.Motivo);m.Parameters.AddWithValue("@Usuario",u);var(ok,msg,_)=Out(m,false);await c.OpenAsync(ct);await m.ExecuteNonQueryAsync(ct);return Result(ok,msg,null);}
 public async Task<List<CompensacionListaDto>> ListarAsync(int e,string est,CancellationToken ct){var l=new List<CompensacionListaDto>();await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_listar");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))l.Add(new(){IdCompensacion=I(r,"Id_Compensacion"),Numero=S(r,"Numero"),Fecha=DT(r,"Fecha"),Persona=S(r,"Persona"),Concepto=S(r,"Concepto"),ImporteAplicado=D(r,"ImporteAplicado"),CuotasAfectadas=I(r,"CuotasAfectadas"),EstadoCodigo=S(r,"Flg_Estado"),Estado=S(r,"Estado")});return l;}
 public async Task<CompensacionDocumentoDto?> ObtenerAsync(int e,string est,int id,CancellationToken ct){await using var c=new SqlConnection(GetConnectionString());await using var m=Cmd(c,"comp.p_obtener");m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@IdCompensacion",id);await c.OpenAsync(ct);await using var r=await m.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;var d=new CompensacionDocumentoDto{IdCompensacion=I(r,"Id_Compensacion"),Numero=S(r,"Numero"),Fecha=DT(r,"Fecha"),Persona=S(r,"Persona"),Documento=S(r,"Documento"),Concepto=S(r,"Concepto"),ImporteAplicado=D(r,"ImporteAplicado"),IdObligacion=I(r,"Id_Obligacion"),ImporteObligacion=D(r,"ImporteObligacion"),SaldoFavorActual=D(r,"SaldoFavorActual"),Observacion=S(r,"Observacion"),EstadoCodigo=S(r,"Flg_Estado")};if(await r.NextResultAsync(ct))while(await r.ReadAsync(ct))d.Detalle.Add(MapDetalle(r));d.CuotasAfectadas=d.Detalle.Count;return d;}
 private static void AddBase(SqlCommand m,int e,string est,CompensacionSimularRequestDto x){m.Parameters.AddWithValue("@id_empresa",e);m.Parameters.AddWithValue("@id_est",est);m.Parameters.AddWithValue("@Cod_TipAnex",x.CodTipAnex);m.Parameters.AddWithValue("@Cod_Anxo",x.CodAnxo);m.Parameters.AddWithValue("@Id_Obligacion",x.IdObligacion);m.Parameters.AddWithValue("@IdsPrestamo",string.Join(',',x.IdsPrestamo));m.Parameters.AddWithValue("@FechaCorte",x.FechaCorte);m.Parameters.AddWithValue("@Importe",x.Importe);m.Parameters.AddWithValue("@SoloVencidas",x.SoloVencidas);}
 private static (SqlParameter,SqlParameter,SqlParameter?) Out(SqlCommand m,bool id,string idName="@Id"){var o=m.Parameters.Add("@Ok",SqlDbType.Bit);o.Direction=ParameterDirection.Output;var s=m.Parameters.Add("@Mensaje",SqlDbType.VarChar,300);s.Direction=ParameterDirection.Output;SqlParameter? p=null;if(id){p=m.Parameters.Add(idName,SqlDbType.Int);p.Direction=ParameterDirection.Output;}return(o,s,p);}private static CompensacionResultadoDto Result(SqlParameter o,SqlParameter s,SqlParameter? i)=>new(){Ok=o.Value!=DBNull.Value&&Convert.ToBoolean(o.Value),Mensaje=s.Value?.ToString()??"",Id=i==null||i.Value==DBNull.Value?0:Convert.ToInt32(i.Value)};
 private static CompensacionDetalleDto MapDetalle(SqlDataReader r)=>new(){Orden=Has(r,"Orden")?I(r,"Orden"):I(r,"OrdenAplicacion"),IdPrestamo=I(r,"Id_Prestamo"),NroCobranza=S(r,"NroCobranza"),NumCuota=I(r,"NumCuota"),FechaVencimiento=DT(r,Has(r,"FecVenc")?"FecVenc":"Fec_Venc"),SaldoAntes=D(r,"SaldoAntes"),InteresAplicado=D(r,"InteresAplicado"),CapitalAplicado=D(r,"CapitalAplicado"),ImporteAplicado=D(r,"ImporteAplicado"),SaldoDespues=D(r,"SaldoDespues")};private static bool Has(SqlDataReader r,string n){for(var i=0;i<r.FieldCount;i++)if(r.GetName(i).Equals(n,StringComparison.OrdinalIgnoreCase))return true;return false;}private static string S(SqlDataReader r,string n)=>r[n]==DBNull.Value?"":r[n].ToString()!.Trim();private static int I(SqlDataReader r,string n)=>r[n]==DBNull.Value?0:Convert.ToInt32(r[n]);private static decimal D(SqlDataReader r,string n)=>r[n]==DBNull.Value?0:Convert.ToDecimal(r[n]);private static DateTime DT(SqlDataReader r,string n)=>r[n]==DBNull.Value?default:Convert.ToDateTime(r[n]);
}
