using Aplicacion.Common;using Aplicacion.Interfaces;using Dominio.DTO.Flota;using Infraestructura.Interfaces;
namespace Aplicacion.CasosUso;
public class FlotaService:IFlotaService
{const int Empresa=6;const string Est="4";readonly IFlotaRepository _repo;public FlotaService(IFlotaRepository repo)=>_repo=repo;
 // TODO: Empresa y estacion son temporales de desarrollo. Deben salir de tenant/sesion/configuracion real.
 static JsonResponseRequest<T> R<T>(T data,bool ok=true,string msg="")=>new(){Success=ok,Data=data,Mensaje=msg,Errors=ok?new():new(){msg}};
 public async Task<JsonResponseRequest<FlotaCatalogosDto>> CatalogosAsync(CancellationToken ct)=>R(await _repo.CatalogosAsync(Empresa,Est,ct));
 public async Task<JsonResponseRequest<List<FlotaDashboardDto>>> DashboardAsync(DateTime fecha,CancellationToken ct)=>R(await _repo.DashboardAsync(Empresa,Est,fecha.Date,ct));
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearVehiculoAsync(int u,FlotaVehiculoCrearDto x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Placa)||string.IsNullOrWhiteSpace(x.Marca)||string.IsNullOrWhiteSpace(x.Modelo))return R(new FlotaResultadoDto(),false,"Completa placa, marca y modelo.");var d=await _repo.CrearVehiculoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearChoferAsync(int u,FlotaChoferCrearDto x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Nombres))return R(new FlotaResultadoDto(),false,"Ingresa el nombre del conductor.");var d=await _repo.CrearChoferAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearContratoAsync(int u,FlotaContratoCrearDto x,CancellationToken ct){if(x.IdVehiculo<=0||x.IdChofer<=0||x.TarifaDia<=0)return R(new FlotaResultadoDto(),false,"Selecciona vehiculo, conductor y tarifa.");var d=await _repo.CrearContratoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> GuardarDiaAsync(int u,FlotaTrabajoDiaDto x,CancellationToken ct){if(x.IdContrato<=0||string.IsNullOrWhiteSpace(x.CodMotivo))return R(new FlotaResultadoDto(),false,"Selecciona contrato y motivo.");var d=await _repo.GuardarDiaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<List<FlotaContratoAdminDto>>> ContratosAdminAsync(CancellationToken ct)=>R(await _repo.ContratosAdminAsync(Empresa,Est,ct));
 public async Task<JsonResponseRequest<FlotaCalendarioDto>> CalendarioAsync(int id,int anio,int mes,CancellationToken ct){if(id<=0||mes<1||mes>12)return R(new FlotaCalendarioDto(),false,"Selecciona contrato y mes.");return R(await _repo.CalendarioAsync(Empresa,Est,id,anio,mes,ct));}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> GenerarReciboAsync(int u,FlotaReciboGenerarDto x,CancellationToken ct){if(x.IdContrato<=0||x.FechaInicio==default||x.FechaFin<x.FechaInicio)return R(new FlotaReciboResultadoDto(),false,"El periodo del recibo no es valido.");var d=await _repo.GenerarReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> GenerarManualAsync(int u,FlotaReciboManualDto x,CancellationToken ct){if(x.IdContrato<=0||x.Fechas.Count==0||x.TarifaDia<=0)return R(new FlotaReciboResultadoDto(),false,"Selecciona dias y una tarifa valida.");x.ModoAgrupacion=x.ModoAgrupacion=="R"?"R":"U";var d=await _repo.GenerarManualAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> RegistrarPagoAsync(int u,FlotaPagoReciboDto x,CancellationToken ct){if(x.IdReciboAlquiler<=0||x.Importe<=0||string.IsNullOrWhiteSpace(x.MedioPago))return R(new FlotaReciboResultadoDto(),false,"Completa recibo, importe y medio de pago.");var d=await _repo.RegistrarPagoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<List<FlotaReciboDto>>> ListarRecibosAsync(int id,int? anio,int? mes,CancellationToken ct)=>R(await _repo.ListarRecibosAsync(Empresa,Est,id,anio,mes,ct));
 public async Task<JsonResponseRequest<FlotaReciboDetalleDto>> ObtenerReciboAsync(int id,CancellationToken ct){var d=await _repo.ObtenerReciboAsync(Empresa,Est,id,ct);return d==null?R(new FlotaReciboDetalleDto(),false,"Recibo no encontrado."):R(d);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularReciboAsync(int u,FlotaReciboAnularDto x,CancellationToken ct){if(x.IdReciboAlquiler<=0)return R(new FlotaResultadoDto(),false,"Selecciona un recibo valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> QuitarDiaReciboAsync(int u,FlotaReciboQuitarDiaDto x,CancellationToken ct){if(x.IdReciboDetalle<=0)return R(new FlotaResultadoDto(),false,"Selecciona un detalle valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.QuitarDiaReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> EditarPagoReciboAsync(int u,FlotaPagoReciboEditarDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");if(x.Importe<=0)return R(new FlotaResultadoDto(),false,"El importe debe ser mayor que cero.");if(string.IsNullOrWhiteSpace(x.MedioPago))return R(new FlotaResultadoDto(),false,"Selecciona el medio de pago.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.EditarPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularPagoReciboAsync(int u,FlotaPagoReciboAnularDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> ValidarPagoReciboAsync(int u,FlotaPagoReciboValidarDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");x.FlgValidado=(x.FlgValidado??"").Trim().ToUpperInvariant();if(x.FlgValidado!="S"&&x.FlgValidado!="N")return R(new FlotaResultadoDto(),false,"FlgValidado invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.ValidarPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CorregirOperacionDiaAsync(int u,FlotaOperacionDiaCorregirDto x,CancellationToken ct){if(x.IdOperacionDia<=0)return R(new FlotaResultadoDto(),false,"Selecciona una operacion valida.");x.FlgTrabajo=(x.FlgTrabajo??"").Trim().ToUpperInvariant();x.FlgCobrable=(x.FlgCobrable??"").Trim().ToUpperInvariant();if(x.FlgTrabajo!="S"&&x.FlgTrabajo!="N")return R(new FlotaResultadoDto(),false,"FlgTrabajo invalido. Usa S o N.");if(x.FlgCobrable!="S"&&x.FlgCobrable!="N")return R(new FlotaResultadoDto(),false,"FlgCobrable invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.CodMotivo))return R(new FlotaResultadoDto(),false,"Selecciona el motivo del dia.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");if(x.KmInicial.HasValue&&x.KmInicial.Value<0||x.KmFinal.HasValue&&x.KmFinal.Value<0)return R(new FlotaResultadoDto(),false,"Kilometraje invalido.");if(x.KmInicial.HasValue&&x.KmFinal.HasValue&&x.KmFinal.Value<x.KmInicial.Value)return R(new FlotaResultadoDto(),false,"El km final no puede ser menor que el km inicial.");if(x.FechaHoraInicio.HasValue&&x.FechaHoraFin.HasValue&&x.FechaHoraFin.Value<x.FechaHoraInicio.Value)return R(new FlotaResultadoDto(),false,"La hora final no puede ser menor que la hora inicial.");var d=await _repo.CorregirOperacionDiaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaEstacionMobileDto>> EstacionMobileAsync(CancellationToken ct)=>R(new FlotaEstacionMobileDto{Contratos=await _repo.ContratosAdminAsync(Empresa,Est,ct),FechaOperacion=DateTime.Today});
 public async Task<JsonResponseRequest<FlotaOperacionMobileDetalleDto>> ObtenerOperacionMobileAsync(FlotaOperacionMobileConsultaDto x,CancellationToken ct){if(x.IdContrato<=0)return R(new FlotaOperacionMobileDetalleDto(),false,"Selecciona un contrato valido.");if(x.Fecha==default)x.Fecha=DateTime.Today;var d=await _repo.ObtenerOperacionMobileAsync(Empresa,Est,x,ct);return d.Contrato==null?R(new FlotaOperacionMobileDetalleDto(),false,"Contrato no encontrado o inactivo."):R(d);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> GuardarOperacionMobileAsync(int u,FlotaOperacionMobileGuardarDto x,CancellationToken ct){if(x.IdContrato<=0)return R(new FlotaResultadoDto(),false,"Selecciona un contrato valido.");x.FlgTrabajo=(x.FlgTrabajo??"").Trim().ToUpperInvariant();x.FlgCobrable=(x.FlgCobrable??"").Trim().ToUpperInvariant();x.FlgPagoCombustible=string.IsNullOrWhiteSpace(x.FlgPagoCombustible)?null:x.FlgPagoCombustible.Trim().ToUpperInvariant();x.ModoRegistro=string.IsNullOrWhiteSpace(x.ModoRegistro)?null:x.ModoRegistro.Trim().ToUpperInvariant();if(x.FlgTrabajo!="S"&&x.FlgTrabajo!="N")return R(new FlotaResultadoDto(),false,"FlgTrabajo invalido. Usa S o N.");if(x.FlgCobrable!="S"&&x.FlgCobrable!="N")return R(new FlotaResultadoDto(),false,"FlgCobrable invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.CodMotivo))return R(new FlotaResultadoDto(),false,"Selecciona el motivo del dia.");if(x.KmInicial.HasValue&&x.KmInicial.Value<0||x.KmFinal.HasValue&&x.KmFinal.Value<0)return R(new FlotaResultadoDto(),false,"Kilometraje invalido.");if(x.KmInicial.HasValue&&x.KmFinal.HasValue&&x.KmFinal.Value<x.KmInicial.Value)return R(new FlotaResultadoDto(),false,"El km final no puede ser menor que el km inicial.");if(x.FechaHoraInicio.HasValue&&x.FechaHoraFin.HasValue&&x.FechaHoraFin.Value<x.FechaHoraInicio.Value)return R(new FlotaResultadoDto(),false,"La hora final no puede ser menor que la hora inicial.");if(x.GalonesCargados<0)return R(new FlotaResultadoDto(),false,"GalonesCargados invalido.");if(x.ImporteCombustible<0)return R(new FlotaResultadoDto(),false,"ImporteCombustible invalido.");var d=await _repo.GuardarOperacionMobileAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> RegistrarCombustibleOperacionAsync(int u,FlotaCombustibleRegistrarDto x,CancellationToken ct){if(x.IdContrato<=0||x.IdChofer<=0||x.IdVehiculo<=0)return R(new FlotaResultadoDto(),false,"Completa contrato, chofer y vehiculo.");if(x.IdOperacionDia.HasValue&&x.IdOperacionDia.Value<=0)return R(new FlotaResultadoDto(),false,"IdOperacionDia invalido.");x.FlgPagoCombustible=string.IsNullOrWhiteSpace(x.FlgPagoCombustible)?null:x.FlgPagoCombustible.Trim().ToUpperInvariant();if(x.Galones<=0)return R(new FlotaResultadoDto(),false,"Galones debe ser mayor que cero.");if(x.Importe<0)return R(new FlotaResultadoDto(),false,"Importe invalido.");if(x.FlgPagoCombustible!=null&&x.FlgPagoCombustible!="C"&&x.FlgPagoCombustible!="D"&&x.FlgPagoCombustible!="P")return R(new FlotaResultadoDto(),false,"FlgPagoCombustible invalido. Usa C, D o P.");var d=await _repo.RegistrarCombustibleOperacionAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaCombustibleListadoDto>> ListarCombustiblePorContratoFechaAsync(int idContrato,DateTime fecha,CancellationToken ct){if(idContrato<=0)return R(new FlotaCombustibleListadoDto(),false,"Selecciona un contrato valido.");if(fecha==default)fecha=DateTime.Today;return R(await _repo.ListarCombustiblePorContratoFechaAsync(Empresa,Est,idContrato,fecha.Date,ct));}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularCombustibleOperacionAsync(int u,FlotaCombustibleAnularDto x,CancellationToken ct){if(x.IdCombustibleOperacion<=0)return R(new FlotaResultadoDto(),false,"Selecciona una carga de combustible valida.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularCombustibleOperacionAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> RegistrarPagoContratoAsync(int u,FlotaPagoContratoRegistrarDto x,CancellationToken ct){if(x.IdContrato<=0||x.IdChofer<=0||x.IdVehiculo<=0)return R(new FlotaResultadoDto(),false,"Completa contrato, chofer y vehiculo.");if(x.IdOperacionDia.HasValue&&x.IdOperacionDia.Value<=0)return R(new FlotaResultadoDto(),false,"IdOperacionDia invalido.");if(x.Importe<=0)return R(new FlotaResultadoDto(),false,"El importe debe ser mayor que cero.");if(x.IdFormaPago<=0)return R(new FlotaResultadoDto(),false,"Selecciona una forma de pago valida.");var d=await _repo.RegistrarPagoContratoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> EditarPagoContratoMobileAsync(int u,FlotaPagoContratoEditarMobileDto x,CancellationToken ct){if(x.IdPagoContrato<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago declarado valido.");if(x.Importe<=0)return R(new FlotaResultadoDto(),false,"El importe debe ser mayor que cero.");if(x.IdFormaPago<=0)return R(new FlotaResultadoDto(),false,"Selecciona una forma de pago valida.");x.OperacionReferencia=string.IsNullOrWhiteSpace(x.OperacionReferencia)?null:x.OperacionReferencia.Trim();x.Observacion=string.IsNullOrWhiteSpace(x.Observacion)?null:x.Observacion.Trim();var d=await _repo.EditarPagoContratoMobileAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaPagoContratoDto>> ObtenerPagoContratoAsync(int idPagoContrato,CancellationToken ct){if(idPagoContrato<=0)return R(new FlotaPagoContratoDto(),false,"Selecciona un pago declarado valido.");var d=await _repo.ObtenerPagoContratoAsync(Empresa,Est,idPagoContrato,ct);return d==null?R(new FlotaPagoContratoDto(),false,"PagoContrato no encontrado."):R(d);}
 public async Task<JsonResponseRequest<List<FlotaPagoContratoListItemDto>>> ListarPagosContratoPendientesAsync(int? idContrato,DateTime? fechaDesde,DateTime? fechaHasta,string? texto,CancellationToken ct){if(idContrato.HasValue&&idContrato.Value<=0)return R(new List<FlotaPagoContratoListItemDto>(),false,"Selecciona un contrato valido.");if(fechaDesde.HasValue&&fechaHasta.HasValue&&fechaHasta.Value.Date<fechaDesde.Value.Date)return R(new List<FlotaPagoContratoListItemDto>(),false,"Rango de fechas invalido.");texto=string.IsNullOrWhiteSpace(texto)?null:texto.Trim();if(texto!=null&&texto.Length>100)texto=texto[..100];return R(await _repo.ListarPagosContratoPendientesAsync(Empresa,Est,idContrato,fechaDesde,fechaHasta,texto,ct));}
 public async Task<JsonResponseRequest<List<FlotaPagoContratoListItemDto>>> ListarPagosContratoPorContratoAsync(int idContrato,string? flgValidado,string? flgEstado,CancellationToken ct){if(idContrato<=0)return R(new List<FlotaPagoContratoListItemDto>(),false,"Selecciona un contrato valido.");flgValidado=string.IsNullOrWhiteSpace(flgValidado)?null:flgValidado.Trim().ToUpperInvariant();flgEstado=string.IsNullOrWhiteSpace(flgEstado)?null:flgEstado.Trim().ToUpperInvariant();if(flgValidado!=null&&flgValidado!="S"&&flgValidado!="N")return R(new List<FlotaPagoContratoListItemDto>(),false,"FlgValidado invalido. Usa S o N.");if(flgEstado!=null&&flgEstado!="A"&&flgEstado!="X")return R(new List<FlotaPagoContratoListItemDto>(),false,"FlgEstado invalido. Usa A o X.");return R(await _repo.ListarPagosContratoAsync(Empresa,Est,idContrato,flgValidado,flgEstado,ct));}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> ValidarPagoContratoAsync(int u,FlotaPagoContratoValidarDto x,CancellationToken ct){if(x.IdPagoContrato<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago declarado valido.");x.FlgValidado=(x.FlgValidado??"").Trim().ToUpperInvariant();if(x.FlgValidado!="S"&&x.FlgValidado!="N")return R(new FlotaResultadoDto(),false,"FlgValidado invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.ValidarPagoContratoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularPagoContratoAsync(int u,FlotaPagoContratoAnularDto x,CancellationToken ct){if(x.IdPagoContrato<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago declarado valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularPagoContratoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> RegistrarAdjuntoFlotaAsync(int u,FlotaAdjuntoRegistrarDto x,CancellationToken ct){x.TipoEntidad=(x.TipoEntidad??"").Trim().ToUpperInvariant();x.TipoAdjunto=(x.TipoAdjunto??"").Trim().ToUpperInvariant();if(x.IdEntidad<=0)return R(new FlotaResultadoDto(),false,"Selecciona una entidad valida.");if(x.TipoEntidad!="OPERACION_DIA"&&x.TipoEntidad!="PAGO_CONTRATO"&&x.TipoEntidad!="RECIBO"&&x.TipoEntidad!="COMBUSTIBLE")return R(new FlotaResultadoDto(),false,"TipoEntidad invalido.");if(x.TipoAdjunto!="RECIBO_GLP"&&x.TipoAdjunto!="VOUCHER_PAGO"&&x.TipoAdjunto!="OTRO")return R(new FlotaResultadoDto(),false,"TipoAdjunto invalido.");if(string.IsNullOrWhiteSpace(x.RutaArchivo))return R(new FlotaResultadoDto(),false,"RutaArchivo es obligatoria.");var d=await _repo.RegistrarAdjuntoFlotaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<List<FlotaAdjuntoDto>>> ListarAdjuntosFlotaAsync(string tipoEntidad,int idEntidad,CancellationToken ct){tipoEntidad=(tipoEntidad??"").Trim().ToUpperInvariant();if(idEntidad<=0)return R(new List<FlotaAdjuntoDto>(),false,"Selecciona una entidad valida.");if(tipoEntidad!="OPERACION_DIA"&&tipoEntidad!="PAGO_CONTRATO"&&tipoEntidad!="RECIBO"&&tipoEntidad!="COMBUSTIBLE")return R(new List<FlotaAdjuntoDto>(),false,"TipoEntidad invalido.");return R(await _repo.ListarAdjuntosFlotaAsync(Empresa,Est,tipoEntidad,idEntidad,ct));}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularAdjuntoFlotaAsync(int u,FlotaAdjuntoAnularDto x,CancellationToken ct){if(x.IdAdjunto<=0)return R(new FlotaResultadoDto(),false,"Selecciona un adjunto valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularAdjuntoFlotaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaUsuarioMobileSesionDto>> LoginMobileAsync(FlotaMobileLoginDto x,CancellationToken ct){x.Telefono=(x.Telefono??"").Trim();x.Pin=(x.Pin??"").Trim();if(string.IsNullOrWhiteSpace(x.Telefono))return R(new FlotaUsuarioMobileSesionDto(),false,"Ingresa el telefono.");if(string.IsNullOrWhiteSpace(x.Pin))return R(new FlotaUsuarioMobileSesionDto(),false,"Ingresa el PIN o contrasena temporal.");var user=await _repo.ObtenerUsuarioMobileLoginAsync(Empresa,Est,x.Telefono,ct);if(user==null)return R(new FlotaUsuarioMobileSesionDto(),false,"Telefono o PIN invalido.");if(!FlotaMobilePasswordHasher.Verify(x.Pin,user.PasswordHash,user.PasswordSalt))return R(new FlotaUsuarioMobileSesionDto(),false,"Telefono o PIN invalido.");return R(new FlotaUsuarioMobileSesionDto{IdUsuarioMobile=user.IdUsuarioMobile,IdChofer=user.IdChofer,IdContrato=user.IdContrato,Telefono=user.Telefono,Nombre=user.Nombre});}
 public Task<int?> ObtenerContratoPorOperacionDiaAsync(int idOperacionDia,CancellationToken ct)=>idOperacionDia<=0?Task.FromResult<int?>(null):_repo.ObtenerContratoPorOperacionDiaAsync(Empresa,Est,idOperacionDia,ct);
 public Task<int?> ObtenerContratoPorPagoContratoAsync(int idPagoContrato,CancellationToken ct)=>idPagoContrato<=0?Task.FromResult<int?>(null):_repo.ObtenerContratoPorPagoContratoAsync(Empresa,Est,idPagoContrato,ct);
 public Task<int?> ObtenerContratoPorCombustibleAsync(int idCombustibleOperacion,CancellationToken ct)=>idCombustibleOperacion<=0?Task.FromResult<int?>(null):_repo.ObtenerContratoPorCombustibleAsync(Empresa,Est,idCombustibleOperacion,ct);
}
