using Aplicacion.Common;using Aplicacion.Interfaces;using Dominio.DTO.Flota;using Infraestructura.Interfaces;
namespace Aplicacion.CasosUso;
public class FlotaService:IFlotaService
{const int Empresa=6;const string Est="4";readonly IFlotaRepository _repo;public FlotaService(IFlotaRepository repo)=>_repo=repo;
 // TODO: Empresa y estacion son temporales de desarrollo. Deben salir de tenant/sesion/configuracion real.
 static JsonResponseRequest<T> R<T>(T data,bool ok=true,string msg="")=>new(){Success=ok,Data=data,Mensaje=msg,Errors=ok?new():new(){msg}};
 public async Task<JsonResponseRequest<FlotaCatalogosDto>> CatalogosAsync(CancellationToken ct)=>R(await _repo.CatalogosAsync(Empresa,Est,ct));
 public async Task<JsonResponseRequest<List<FlotaDashboardDto>>> DashboardAsync(DateTime fecha,CancellationToken ct)=>R(await _repo.DashboardAsync(Empresa,Est,fecha.Date,ct));
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearVehiculoAsync(int u,FlotaVehiculoCrearDto x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Placa)||string.IsNullOrWhiteSpace(x.Marca)||string.IsNullOrWhiteSpace(x.Modelo))return R(new FlotaResultadoDto(),false,"Completa placa, marca y modelo.");var d=await _repo.CrearVehiculoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearChoferAsync(int u,FlotaChoferCrearDto x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Nombres))return R(new FlotaResultadoDto(),false,"Ingresa el nombre del conductor.");var d=await _repo.CrearChoferAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CrearContratoAsync(int u,FlotaContratoCrearDto x,CancellationToken ct){if(x.IdVehiculo<=0||x.IdChofer<=0||x.TarifaDia<=0)return R(new FlotaResultadoDto(),false,"Selecciona vehiculo, conductor y tarifa.");var d=await _repo.CrearContratoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> GuardarDiaAsync(int u,FlotaTrabajoDiaDto x,CancellationToken ct){if(x.IdContrato<=0||string.IsNullOrWhiteSpace(x.CodMotivo))return R(new FlotaResultadoDto(),false,"Selecciona contrato y motivo.");var d=await _repo.GuardarDiaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<List<FlotaContratoAdminDto>>> ContratosAdminAsync(CancellationToken ct)=>R(await _repo.ContratosAdminAsync(Empresa,Est,ct));
 public async Task<JsonResponseRequest<FlotaCalendarioDto>> CalendarioAsync(int id,int anio,int mes,CancellationToken ct){if(id<=0||mes<1||mes>12)return R(new FlotaCalendarioDto(),false,"Selecciona contrato y mes.");return R(await _repo.CalendarioAsync(Empresa,Est,id,anio,mes,ct));}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> GenerarReciboAsync(int u,FlotaReciboGenerarDto x,CancellationToken ct){if(x.IdContrato<=0||x.FechaInicio==default||x.FechaFin<x.FechaInicio)return R(new FlotaReciboResultadoDto(),false,"El periodo del recibo no es valido.");var d=await _repo.GenerarReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> GenerarManualAsync(int u,FlotaReciboManualDto x,CancellationToken ct){if(x.IdContrato<=0||x.Fechas.Count==0||x.TarifaDia<=0)return R(new FlotaReciboResultadoDto(),false,"Selecciona dias y una tarifa valida.");x.ModoAgrupacion=x.ModoAgrupacion=="R"?"R":"U";var d=await _repo.GenerarManualAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaReciboResultadoDto>> RegistrarPagoAsync(int u,FlotaPagoReciboDto x,CancellationToken ct){if(x.IdReciboAlquiler<=0||x.Importe<=0||string.IsNullOrWhiteSpace(x.MedioPago))return R(new FlotaReciboResultadoDto(),false,"Completa recibo, importe y medio de pago.");var d=await _repo.RegistrarPagoAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<List<FlotaReciboDto>>> ListarRecibosAsync(int id,int? anio,int? mes,CancellationToken ct)=>R(await _repo.ListarRecibosAsync(Empresa,Est,id,anio,mes,ct));
 public async Task<JsonResponseRequest<FlotaReciboDetalleDto>> ObtenerReciboAsync(int id,CancellationToken ct){var d=await _repo.ObtenerReciboAsync(Empresa,Est,id,ct);return d==null?R(new FlotaReciboDetalleDto(),false,"Recibo no encontrado."):R(d);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularReciboAsync(int u,FlotaReciboAnularDto x,CancellationToken ct){if(x.IdReciboAlquiler<=0)return R(new FlotaResultadoDto(),false,"Selecciona un recibo valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> QuitarDiaReciboAsync(int u,FlotaReciboQuitarDiaDto x,CancellationToken ct){if(x.IdReciboDetalle<=0)return R(new FlotaResultadoDto(),false,"Selecciona un detalle valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.QuitarDiaReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> EditarPagoReciboAsync(int u,FlotaPagoReciboEditarDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");if(x.Importe<=0)return R(new FlotaResultadoDto(),false,"El importe debe ser mayor que cero.");if(string.IsNullOrWhiteSpace(x.MedioPago))return R(new FlotaResultadoDto(),false,"Selecciona el medio de pago.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.EditarPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> AnularPagoReciboAsync(int u,FlotaPagoReciboAnularDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.AnularPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> ValidarPagoReciboAsync(int u,FlotaPagoReciboValidarDto x,CancellationToken ct){if(x.IdPagoRecibo<=0)return R(new FlotaResultadoDto(),false,"Selecciona un pago valido.");x.FlgValidado=(x.FlgValidado??"").Trim().ToUpperInvariant();if(x.FlgValidado!="S"&&x.FlgValidado!="N")return R(new FlotaResultadoDto(),false,"FlgValidado invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.ValidarPagoReciboAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
 public async Task<JsonResponseRequest<FlotaResultadoDto>> CorregirOperacionDiaAsync(int u,FlotaOperacionDiaCorregirDto x,CancellationToken ct){if(x.IdOperacionDia<=0)return R(new FlotaResultadoDto(),false,"Selecciona una operacion valida.");x.FlgTrabajo=(x.FlgTrabajo??"").Trim().ToUpperInvariant();x.FlgCobrable=(x.FlgCobrable??"").Trim().ToUpperInvariant();if(x.FlgTrabajo!="S"&&x.FlgTrabajo!="N")return R(new FlotaResultadoDto(),false,"FlgTrabajo invalido. Usa S o N.");if(x.FlgCobrable!="S"&&x.FlgCobrable!="N")return R(new FlotaResultadoDto(),false,"FlgCobrable invalido. Usa S o N.");if(string.IsNullOrWhiteSpace(x.CodMotivo))return R(new FlotaResultadoDto(),false,"Selecciona el motivo del dia.");if(string.IsNullOrWhiteSpace(x.Motivo))return R(new FlotaResultadoDto(),false,"Ingresa el motivo.");var d=await _repo.CorregirOperacionDiaAsync(Empresa,Est,u,x,ct);return R(d,d.Ok,d.Mensaje);}
}
