using Aplicacion.Common;
using Aplicacion.Interfaces;
using Dominio.DTO.Refinanciamiento;
using Infraestructura.Interfaces;
using ClosedXML.Excel;

namespace Aplicacion.CasosUso;
public class RefinanciamientoService : IRefinanciamientoService
{
    private const int Empresa=6;private const string Est="4";private readonly IRefinanciamientoRepository _repo;
    public RefinanciamientoService(IRefinanciamientoRepository repo)=>_repo=repo;
    public async Task<JsonResponseRequest<List<RefinanciamientoPrestamoDto>>> PrestamosClienteAsync(string t,string a,DateTime f,CancellationToken ct)=>new(){Success=true,Data=await _repo.PrestamosClienteAsync(Empresa,Est,t,a,f,ct),Mensaje="Prestamos cargados."};
    public async Task<JsonResponseRequest<RefinanciamientoCalculoDto>> CalcularAsync(RefinanciamientoCalcularRequestDto r,CancellationToken ct){if(r.IdsPrestamo.Count==0)return Fail<RefinanciamientoCalculoDto>("Seleccione al menos un prestamo.");var x=await _repo.CalcularAsync(Empresa,Est,r,ct);return x==null?Fail<RefinanciamientoCalculoDto>("No se pudo consolidar la deuda. Revise importes y seleccion."):new(){Success=true,Data=x,Mensaje="Deuda consolidada correctamente."};}
    public async Task<JsonResponseRequest<RefinanciamientoAplicarResultadoDto>> AplicarAsync(int u,RefinanciamientoAplicarRequestDto r,CancellationToken ct){if(r.IdsPrestamo.Count==0||r.PorcInteresMensual<=0||r.FechaFin<r.FechaInicio)return Fail<RefinanciamientoAplicarResultadoDto>("Revise prestamos, tasa y fechas.");var x=await _repo.AplicarAsync(Empresa,Est,u,r,ct);return new(){Success=x.Ok,Data=x,Mensaje=x.Mensaje};}
    public async Task<JsonResponseRequest<List<RefinanciamientoListaDto>>> ListarAsync(CancellationToken ct)=>new(){Success=true,Data=await _repo.ListarAsync(Empresa,Est,ct),Mensaje="Operaciones cargadas."};
    public async Task<(byte[] Archivo,string Nombre,string Tipo,string? Error)> ExportarPdfAsync(int id,CancellationToken ct){var d=await _repo.ObtenerAsync(Empresa,Est,id,ct);return d==null?(Array.Empty<byte>(),"","application/pdf","Operacion no encontrada."):(RefinanciamientoPdfBuilder.Build(d),$"Refinanciamiento_{id}_{DateTime.Now:yyyyMMdd}.pdf","application/pdf",null);}
    public async Task<(byte[] Archivo,string Nombre,string Tipo,string? Error)> ExportarExcelAsync(int id,CancellationToken ct){var d=await _repo.ObtenerAsync(Empresa,Est,id,ct);if(d==null)return(Array.Empty<byte>(),"","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Operacion no encontrada.");using var w=new XLWorkbook();var s=w.Worksheets.Add("Refinanciamiento");s.Cell("A1").Value="REFINANCIACION FORMAL";s.Range("A1:F1").Merge().Style.Fill.BackgroundColor=XLColor.FromHtml("183153");s.Range("A1:F1").Style.Font.FontColor=XLColor.White;s.Range("A1:F1").Style.Font.Bold=true;s.Range("A3:B12").Style.Border.BottomBorder=XLBorderStyleValues.Hair;s.Cell("A3").Value="Cliente";s.Cell("B3").Value=d.Cliente;s.Cell("A4").Value="Documento";s.Cell("B4").Value=d.Documento;s.Cell("A5").Value="Operacion";s.Cell("B5").Value=d.IdRefinanciamiento;s.Cell("A6").Value="Prestamo nuevo";s.Cell("B6").Value=d.IdPrestamoNuevo;s.Cell("A7").Value="Capital consolidado";s.Cell("B7").Value=d.CapitalRefinanciado;s.Cell("A8").Value="Interes nuevo";s.Cell("B8").Value=d.InteresNuevo;s.Cell("A9").Value="Total nuevo";s.Cell("B9").Value=d.TotalNuevo;s.Cell("A10").Value="Tasa mensual";s.Cell("B10").Value=d.PorcInteresMensual/100;s.Cell("A11").Value="Inicio";s.Cell("B11").Value=d.FechaInicio;s.Cell("A12").Value="Fin";s.Cell("B12").Value=d.FechaFin;s.Cell("B7").Style.NumberFormat.Format="S/. #,##0.00";s.Range("B8:B9").Style.NumberFormat.Format="S/. #,##0.00";s.Cell("B10").Style.NumberFormat.Format="0.0000%";var row=15;s.Cell(row,1).Value="Cuota";s.Cell(row,2).Value="Vencimiento";s.Cell(row,3).Value="Capital";s.Cell(row,4).Value="Interes";s.Cell(row,5).Value="Importe";s.Range(row,1,row,5).Style.Fill.BackgroundColor=XLColor.FromHtml("EAF0F7");s.Range(row,1,row,5).Style.Font.Bold=true;foreach(var q in d.Cuotas){row++;s.Cell(row,1).Value=q.Numero;s.Cell(row,2).Value=q.Vencimiento;s.Cell(row,3).Value=q.Capital;s.Cell(row,4).Value=q.Interes;s.Cell(row,5).Value=q.Importe;}s.Range(16,3,row,5).Style.NumberFormat.Format="S/. #,##0.00";s.Columns().AdjustToContents();using var ms=new MemoryStream();w.SaveAs(ms);return(ms.ToArray(),$"Refinanciamiento_{id}_{DateTime.Now:yyyyMMdd}.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",null);}
    public async Task<JsonResponseRequest<RefinanciamientoCronogramaDto>> SimularCronogramaAsync(RefinanciamientoCronogramaRequestDto r,CancellationToken ct){if(r.Capital<=0||r.PorcInteresMensual<=0||r.FechaFin<r.FechaInicio)return Fail<RefinanciamientoCronogramaDto>("Revise capital, tasa y fechas.");var x=await _repo.SimularCronogramaAsync(r,ct);return x==null?Fail<RefinanciamientoCronogramaDto>("No se pudo generar el cronograma."):new(){Success=true,Data=x,Mensaje="Cronograma generado correctamente."};}
    private static JsonResponseRequest<T> Fail<T>(string m)=>new(){Success=false,Mensaje=m,Errors=new(){m}};
}
