namespace Dominio.DTO.Compensacion;

public class CompensacionConceptoDto { public string Codigo { get; set; }=""; public string Nombre { get; set; }=""; }
public class CompensacionObligacionCrearDto { public string CodTipAnex { get; set; }="";public string CodAnxo { get; set; }="";public string CodConcepto { get; set; }="";public DateTime Fecha { get; set; }public decimal Importe { get; set; }public string? Referencia { get; set; }public string? Observacion { get; set; } }
public class CompensacionObligacionDto { public int IdObligacion { get; set; }public DateTime Fecha { get; set; }public string Persona { get; set; }="";public string Concepto { get; set; }="";public decimal Importe { get; set; }public decimal ImporteAplicado { get; set; }public decimal SaldoDisponible { get; set; }public string Referencia { get; set; }="";public string Estado { get; set; }=""; }
public class CompensacionPrestamoDto { public int IdPrestamo { get; set; }public DateTime Fecha { get; set; }public DateTime FechaFinCobro { get; set; }public string Concepto { get; set; }="";public decimal SaldoPendiente { get; set; }public decimal SaldoVencido { get; set; }public int CuotasVencidas { get; set; } }
public class CompensacionSimularRequestDto { public string CodTipAnex { get; set; }="";public string CodAnxo { get; set; }="";public int IdObligacion { get; set; }public List<int> IdsPrestamo { get; set; }=new();public DateTime FechaCorte { get; set; }public decimal Importe { get; set; }public bool SoloVencidas { get; set; }=true; }
public class CompensacionAplicarRequestDto:CompensacionSimularRequestDto { public string Motivo { get; set; }="COM";public string? Observacion { get; set; } }
public class CompensacionDetalleDto { public int Orden { get; set; }public int IdPrestamo { get; set; }public string NroCobranza { get; set; }="";public int NumCuota { get; set; }public DateTime FechaVencimiento { get; set; }public decimal SaldoAntes { get; set; }public decimal InteresAplicado { get; set; }public decimal CapitalAplicado { get; set; }public decimal ImporteAplicado { get; set; }public decimal SaldoDespues { get; set; } }
public class CompensacionSimulacionDto { public decimal SaldoFavorAntes { get; set; }public decimal ImporteSolicitado { get; set; }public decimal ImporteAplicado { get; set; }public decimal SaldoFavorDespues { get; set; }public decimal InteresAplicado { get; set; }public decimal CapitalAplicado { get; set; }public int CuotasAfectadas { get; set; }public List<CompensacionDetalleDto> Detalle { get; set; }=new(); }
public class CompensacionResultadoDto { public bool Ok { get; set; }public string Mensaje { get; set; }="";public int Id { get; set; } }
public class CompensacionListaDto { public int IdCompensacion { get; set; }public string Numero { get; set; }="";public DateTime Fecha { get; set; }public string Persona { get; set; }="";public string Concepto { get; set; }="";public decimal ImporteAplicado { get; set; }public int CuotasAfectadas { get; set; }public string EstadoCodigo { get; set; }="";public string Estado { get; set; }=""; }
public class CompensacionRevertirDto { public int IdCompensacion { get; set; }public string Motivo { get; set; }=""; }
public class CompensacionDocumentoDto:CompensacionListaDto { public string Documento { get; set; }="";public int IdObligacion { get; set; }public decimal ImporteObligacion { get; set; }public decimal SaldoFavorActual { get; set; }public string Observacion { get; set; }="";public List<CompensacionDetalleDto> Detalle { get; set; }=new(); }
